### ISSUE TITLE
Add multiple status for tickets 

### ISSUE THREAD

**Issue by maxinjohn** [opensupports/opensupports#103]
Hi,

Please add multiple status for on tickets in addition to open and closed like customer waiting etc...

**Comment by ivandiazwm** [comment]
Interesting, this could be added in a future version.

**Comment by nickbe** [comment]
I would completely cover this with a 'tags' feature as already suggested in another post.
Tags AND the option to filter by and search for tags....

**Comment by mredigonda** [comment]
@nickbe you mean a system similar to current Github's system? That'd be an interesting option.

**Comment by nickbe** [comment]
I have to admit I don't know the Github system very well. But I always imagined that if I have a tag "unconfirmed", then it would be nice to click on that tag have the option to change it to "confirmed", "canceled" or whatever. Like a popup menu over the tag. So tags would have to have some kind of connection among each other. A tag-group if you will. And I would even go so far and just let the user define predefined tags with the tag-name and a tag-group as both simple text fields. 
After that you would just evaluate the tag-group to get the popup menues.
Does that make sense to you?

**Comment by nickbe** [comment]
you're right of course. Let's keep it simple. But what is you define tag groups in the most simple way possible? Then everything else would feel very natural. 

Two fields: name of tag group and tag group items. Example:
Tag group name: "Severity"
Tag group items: "Bug", "Enhancement", "Idea", "Request"

Now you could show a popup selector when I click on the tag "Enhancement" and it would show all the possible values. 

As simple as Github but in its simplicity much more powerful :)

**Comment by nickbe** [comment]
Will this be covered by tags now? I'd agree that this would keep things rather more simple

**Comment by ivandiazwm** [comment]
Yes, this should be covered by tags feature now.
