### ISSUE TITLE
Staff cannot able to open tickets?????

### ISSUE THREAD

**Issue by maxinjohn** [opensupports/opensupports#106]
Staff cannot able to open tickets?????

**Comment by mredigonda** [comment]
Hello, please provide some more information (is there something we can do to replicate the bug?), also sharing information about your operative system and Javascript console outputs would be really helpful.

Thank you!

**Comment by maxinjohn** [comment]
When I try login as a staff, there is no such option to create/open tickets.

**Comment by maxinjohn** [comment]
If there was an option how I should open a ticket as staff  a member  .

![image](https://user-images.githubusercontent.com/33740873/33057662-08ba9ba0-ceb2-11e7-81c9-de37cecf7bc0.png)

Please reply ASAP

**Comment by ivandiazwm** [comment]
Currently, a staff can not create a ticket.

**Comment by microbios2020** [comment]
I can display their items to change
![error](https://user-images.githubusercontent.com/68506781/87877103-fd037000-c9a1-11ea-81c1-f82e17c25a0d.png)

can you help me
