### ISSUE TITLE
Articles - Articulos

### ISSUE THREAD

**Issue by maxiasp** [opensupports/opensupports#108]
In the articles section, I added two "titles" and it does not allow me to add more, it says "incorrect title". If I create new articles with the same name as the previous ones allows me.

En la sección articulos, agregue dos "titulos" y no me permite agregar mas, me dice "titulo incorrecto". Si creo nuevos articulos con el mismo nombre que los anteriores me lo permite

**Comment by ivandiazwm** [comment]
This is caused by this line https://github.com/opensupports/opensupports/blob/master/client/src/lib-app/validations/validations-factory.js#L10

**Comment by mredigonda** [comment]
* What should be the correct minimum size of a title (to edit [this](https://github.com/opensupports/opensupports/blob/master/client/src/lib-app/validations/validations-factory.js#L10))? 
* Should it be possible to have two or more articles with the same name?

**Comment by ivandiazwm** [comment]
@mredigonda I'd say 1 character should be the minimum. Make sure it is in sync with frontend validation.
