### ISSUE TITLE
[Fixed] Infinity loading while setting up the smtp settings

### ISSUE THREAD

**Issue by FoxXxHater** [opensupports/opensupports#1118]
Hello Guys,

i think, i have a problem with my installation. 
because i cant setup my smtp settings. they are ending in a infinity load...

can somone help me please?
i have installed the system with the wizard on a plesk ubuntu web server with all open ports hosted by IONOS

![image](https://user-images.githubusercontent.com/54017453/146648676-91545c7f-811b-4961-8ed0-8123a3da6f77.png)

**Comment by FoxXxHater** [comment]
p.s. 

It doesn't matter what I enter in the fields ... it always ends in a continuous loop!

**Comment by FoxXxHater** [comment]
![image](https://user-images.githubusercontent.com/54017453/146648831-2ab3a1f4-b8b5-4140-a310-33c3a6f0619c.png)

the dev console

**Comment by FoxXxHater** [comment]
The newest

**Comment by FoxXxHater** [comment]
I have tested it one more again, only the error in line 16. (View pick)

**Comment by kirbypls** [comment]
Hi, 

We're this will be fixed in the new version, we plan to release this update before the 2022

Cordially,

Luca.

**Comment by FoxXxHater** [comment]
Okay, that sounds greate!

**Comment by FoxXxHater** [comment]
> Hi,
> 
> We think this will be fixed in the new version, we plan to release this update before the 2022
> 
> Cordially,
> 
> Luca.

How's Looking for the new version?

**Comment by FoxXxHater** [comment]
Okay.

i installed/ updated the new version but the loading loop is the same…

**Comment by kirbypls** [comment]
Did you clear the cache after installing/updating? 
if the answer is yes, did you get any new error in the console?

**Comment by FoxXxHater** [comment]
What cache?

From the Browser or server?

**Comment by kirbypls** [comment]
Browser cache

**Comment by FoxXxHater** [comment]
Oh, no.

I have testet yet. ITS Working with my PC... i think
