### ISSUE TITLE
Ticket not released from owner when assigning to diferent department

### ISSUE THREAD

**Issue by jcbarbosa** [opensupports/opensupports#115]
Assigning a ticket to a different department causes ticket no to be usable.

This is because 'owner' field is not set as null on ticket table (MySQL)
Also the corresponding 'staff_ticket' record is not currently deleted

**Comment by ivandiazwm** [comment]
Thanks for reporting this. I'll add it to our bug list.

**Comment by nickbe** [comment]
That was a lot of moving 🤣 - so is it fixed now?

**Comment by jcbarbosa** [comment]
Sorry we are not currently using this sytem anymore.
Thanks,
João

**Comment by nickbe** [comment]
Well we in fact do. Therefore the question wether the bug is already fixed or not?

**Comment by ivandiazwm** [comment]
The issue is fixed but it is currently on code review and need some updates
