### ISSUE TITLE
Blank page after choosing the language 

### ISSUE THREAD

**Issue by ingenieroti** [opensupports/opensupports#1156]
![Screenshot from 2022-02-15 16-21-47](https://user-images.githubusercontent.com/97553193/154151561-f56a683a-9a62-453e-8f5e-419f0d330cb0.png)

**Comment by mredigonda** [comment]
Hey!

Hmmm, seems similar to this issue, please try to clean up the local storage and then try to re-do the step (described here: https://github.com/opensupports/opensupports/issues/1146#issuecomment-1033222961).

Let me know if that helps.

**Comment by ingenieroti** [comment]
It didn't work for me, I get the same problem again.

**Comment by rtoenniges** [comment]
Got the same problem.

AlmaLinux 8.5
PHP 7.4
httpd 2.4

**Comment by mredigonda** [comment]
Hmmm, we suspect your htaccess configuration might be the culprit here.

Could you please go through this guide: https://docs.opensupports.com/guides/installation/#troubleshooting and let me know if that helps solve the issue?

Thanks guys!

**Comment by rtoenniges** [comment]
Hi, 

my .htaccess is in the root directory /var/www/html/support and contains:
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/?(api)/
RewriteRule .* index.php [PT,L]
```

In my VirtualHost I added the AllowOverride All directive:
```
<VirtualHost *:80>
        DocumentRoot "/var/www/html"

        <Directory "/var/www/html/support">
                RewriteEngine On
                AllowOverride All
        </Directory>

</VirtualHost>
```

but still the same problem.

**Comment by ingenieroti** [comment]
I already solved the problem, if it was a problem of permissions in the directory. Thank you very much!
