### ISSUE TITLE
Installation Bug in Hosting Service PHP 7.x

### ISSUE THREAD

**Issue by ZzGustavo** [opensupports/opensupports#1231]
- ### **The Problem:**
When upload the unzipped files, using FTP, to the hosting service it is not possible to start the installation because a blank screen appears where only the tab icon and its title are loaded.
In the browser console it shows these errors:

>### **O Problema:**
> PT-BR 
> Ao realizar o upload dos arquivos descompactados, por FTP, para o serviço de hospedagem não é possível iniciar a instalação pois aparece uma tela em branco onde só carrega o ícone da aba e seu titulo.
No console do navegador apresenta tais erros:

![erro](https://user-images.githubusercontent.com/1358678/182678882-f6c8abc4-5b8f-45f8-af35-b03b74eb2b61.png)

- ### **About:**
Apparently the errors happen because of a function used in the UTIL.PHP file, on line 60, (`../api/vendor/slim/slim/Slim/Http`) that has been deprecated: **`get_magic_quotes_gpc`** https://www.php.net/manual/pt_BR/function.get-magic-quotes-gpc.php

>### **Sobre:**
> PT-BR 
> Aparentemente os erros acontecem por causa de uma função utilizada no arquivo UTIL.PHP, na linha 60, (`../api/vendor/slim/slim/Slim/Http`) que foi descontinuada: **`get_magic_quotes_gpc`** https://www.php.net/manual/pt_BR/function.get-magic-quotes-gpc.php

![util-error](https://user-images.githubusercontent.com/1358678/182679438-4d851e89-7295-4deb-9099-974023328266.png)

- ### **Solution:**
The line: `$strip = is_null($overrideStripSlashes) ? get_magic_quotes_gpc() : $overrideStripSlashes;` from the **util.php** file should be replaced with: `$strip = $overrideStripSlashes;` then the screen for installing OpenSupport in the browser will appear.

>### **Solução:**
> PT-BR 
>Deverá ser substituida a linha: `$strip = is_null($overrideStripSlashes) ? get_magic_quotes_gpc() : $overrideStripSlashes;` do arquivo **util.php** por:  `$strip = $overrideStripSlashes;` então aparecerá a tela para instalação do OpenSupport no navegador
![util-solution](https://user-images.githubusercontent.com/1358678/182680354-1adf31e1-755c-4891-b2ec-bc7a170f1761.png)

- ### **Result:**
>### **Resultado:**
> PT-BR
![result](https://user-images.githubusercontent.com/1358678/182681634-d5bb3677-aa7e-4222-9a3a-6b14b83edd9d.png)
![FUNCIONANDO](https://user-images.githubusercontent.com/1358678/182670823-fc7f96fe-e844-4833-8ac0-a9671d08483f.png)

**Comment by 2Rios** [comment]
Fala Gustavo, Cara atualizei para aversão 11, mas parece que a aplicação não consegue conectar no Banco, fica no dashboard carregando e não sai disso, mas por exemplo as tags personalizadas que criei na versão 9 ele consegue identificar.. Tens ideia do que possa ser?

**Comment by ZzGustavo** [comment]
> Fala Gustavo, Cara atualizei para aversão 11, mas parece que a aplicação não consegue conectar no Banco, fica no dashboard carregando e não sai disso, mas por exemplo as tags personalizadas que criei na versão 9 ele consegue identificar.. Tens ideia do que possa ser?

Tenta verificar nos arquivos de configuração do banco se foi importado todas as informações
../OpenSupport/api/config.php

**Comment by 2Rios** [comment]
Ta gravando correto sim, criei uma nova vm instalei o Open do zero e na versão 11 não consegue conectar no banco, fica aquele carregando e não vai pra frente. Se instalo a versão 4.9.0 ele funciona normalmente.

**Comment by codsec** [comment]
Eu estou tendo problemas com o banco tbm porem na parte de instalação![Screenshot_1](https://user-images.githubusercontent.com/44205014/189792570-b3bd4527-4dab-4d4f-a87e-450853f09ab3.png)

**Comment by jrfred88** [comment]
Ola, Gustavo eu fiz o que você informou ai, conforme essa foto [Util-php.png](https://i.ibb.co/4dp8z3T/Util-php.png)
mas o mesmo ainda esta dando erro quando tento entrar como http://ip_do_servidor
segue o erro [erro.png](https://i.ibb.co/KXtbfjv/erro.png)

**Comment by ZzGustavo** [comment]
> Ola, Gustavo eu fiz o que você informou ai, conforme essa foto [Util-php.png](https://i.ibb.co/4dp8z3T/Util-php.png) mas o mesmo ainda esta dando erro quando tento entrar como http://ip_do_servidor segue o erro [erro.png](https://i.ibb.co/KXtbfjv/erro.png)

Cara, experimenta limpar o cache e os cookies, pode ser que seja isso

**Comment by dev-ammoreira** [comment]
> Oi, Realizei os procedimentos e no meu continua dando erro. Alguma outra ideia?? Fiz a limpeza do cache também...
> 
> ![image](https://user-images.githubusercontent.com/124625797/217276797-6e1b6ac5-b94f-4719-af59-f1b37c83d233.png)

Após tentar por várias vezes e em vários navegadores diferentes finalmente consegui iniciar a instalação. Só que agora fico to Passo 6. Alguém poderia me ajudar??

![image](https://user-images.githubusercontent.com/124625797/217604594-9f6bf1e1-4c3a-4848-b1da-52e3316bbe66.png)
