### ISSUE TITLE
Ticket button in e-mail doesn't work / Go-To Actions

### ISSUE THREAD

**Issue by Yingwu21** [opensupports/opensupports#139]
In the e-mails that get sent from the ticket system the button that has been added so that your customer can click on it doesn't work in all e-mails.

This also lead me to becoming curious if maybe the Google Go-To Actions (https://developers.google.com/gmail/markup/reference/go-to-action) might be possible to achieve in the automated e-mails. This is in my opinion one of the coolest and cleanest looking indications that the e-mail is about a ticket and immediately acts as a go to ticket button. Gmail and Outlook support this and some other mail clients have started to support it as well.

I'd be interested to hear your opinion on the Go-To Actions button.

**Comment by ivandiazwm** [comment]
The checkbox in "My Account" only enables/disables emails when a new ticket is created. The rest of the emails (response, department, etc.) will continue to be sent.

I haven't consider Go-To Actions, we will take a look. cc// @mredigonda

**Comment by Yingwu21** [comment]
That's not what I meant by the button not working. I meant that the button that is in the default code for sending an e-mail is not clickable to go to your ticket (as I assume is what this button is normally for)

![button not working opensupports](https://user-images.githubusercontent.com/34661434/36356108-463304e6-14ed-11e8-8c03-82a79953c8fb.PNG)

I hope that's more clear for you to look into. And this is the case for all the mails except for the verification mail, that one is clickable.

**Comment by ivandiazwm** [comment]
oh, sure. This a bug then. Thanks!

**Comment by b4allb4u** [comment]
We are also facing the same issue as desired by @Yingwu21 
Pls look into this matter and do the needful action.

**Comment by romuloslv** [comment]
@ivandiazwm Has the button function inside the email body already been resolved?
