### ISSUE TITLE
Suggestion for ticket creation as staff

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#147]
Would it be possible to simply switch between support and staff login. This way staff members could easily create tickets by themselves. Additionally it would be simple to be able to assign tickets directly to other staff members.

**Comment by nickbe** [comment]
Any thoughts about this so far?

**Comment by ivandiazwm** [comment]
I think #175 will cover this scenario

**Comment by nickbe** [comment]
Thanks :)
