### ISSUE TITLE
Trying to install shows blank screen - as mentioned earlier

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#148]
I'm using PHP 5.6.31, The Firefox Console says:

request /system/installation-done 
Object {  }
main.js:63:31376
Object { session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, routing: {…} }
main.js:63:30387
request /system/get-settings 
Object {  }
main.js:63:31376
Object { session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, routing: {…} }
main.js:63:30387
request /user/check-session 
Object {  }
main.js:63:31376
Object { session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, routing: {…} }
main.js:63:30387
INVALID REQUEST
main.js:63:31546
error
main.js:63:31577
Object { session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, routing: {…} }
main.js:63:30387
INVALID REQUEST
main.js:63:31546
error
main.js:63:31577
Object { session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, routing: {…} }
main.js:63:30387
Error: 
main.js:42:28108
INVALID REQUEST
main.js:63:31546
error

I've also tried:  RewriteBase /

**Comment by nickbe** [comment]
Testing on another Server where we can configure Apache to our liking the changes that were suggested on another post worked and the installer could be started.

However the same settings in the .htaccess of my local server failed to work.
It looks the same but obviusly it isn't 😦

**Comment by pekiZG** [comment]
@nickbe are you using nginx?
If the answer is yes check
https://github.com/opensupports/opensupports/issues/54#issuecomment-368277810

**Comment by nickbe** [comment]
No it‘s also Apache but under Windows - using UWAmp.

**Comment by nickbe** [comment]
I correct myself here. It was of course a Linux Server, latest PHP 5.6.x Version. Hoster is Domainfactory (Part of UnitedDomains).

**Comment by pekiZG** [comment]
Now the only question is if they are using nginx or apache.
My spider senses are telling me it's nginx.

**Comment by nickbe** [comment]
Sorry, but no. We never use nginx. It's definetly Apache.

**Comment by pekiZG** [comment]
Tnx, I will try to reproduce it

**Comment by marfabri21** [comment]
hello.
the problem is the config AllowOverride non ein apache.
To fix set AllowOverride All.
Example:

<Directory /var/www/html>
AllowOverride All
</Directory>
</VirtualHost>

**Comment by jinbao-999** [comment]
hello @mvilche 
Your were right. And thanks. It was a great help for me. 
In fact I was giving "AllowOverride" to "None". AllowOverride controls what directives may be placed in .htaccess files. As I set it to "None". ".htaccess" couldn't verify if files needed are in the directory. There's a JavaScript file in Opensupport install package. "bundle.js". Apache server could not start the script and the web page or the installation wizard was blank. When I change 

AllowOverride All

everything was in the right place and Installation Wizard Show up.

**Comment by oghenez** [comment]
Simply changing the php version in wamp64 version 3 to 5.6 solved the problem
