### ISSUE TITLE
Suggestion for User management

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#149]
I'd suggest the following little feature which should work even if "User registration" is disabled.

1. Send Invite:  Let the admin send an invite to a mail adress ("You have been invited to ...... Please complete your signup on our website... and so on). The Link from inside the mail leads to the actual signup, even if the "User registration" has been disabled.

In my case I need to disable the external signup and add users and clients. Especially since I want to prevent anyone else from being able to signup.

2. Let an admin set the user mail as verified AND allow a user to resend the confirmation request email along with the error message "This mail adress has not yet been confirmed".

**Comment by nickbe** [comment]
Hey guys, did you already find the time to review my questions/suggestions?

**Comment by mredigonda** [comment]
Having other means to add users when registration is disabled is a feature requested by many so far (it is actually point 5 in #116), I agree that it should be easier than importing a CSV file, and allowing admins to add users via a 'send invite' button seems an easy way to do it.

About point 2, I don't really think that we should allow admins to set user mails as verified (in theory, mails should be working fine), however, I think that allowing users to resend confirmation mails is a must.

Thank you for your feedback!

**Comment by nickbe** [comment]
Thanks for agreeing with suggestion 1. I think this would really come in handy.

As for point 2. I think you're right. Having point 1 is easy enough to create users. But they still should go through the process of creating their own password.

**Comment by nickbe** [comment]
Any progress yet?
