### ISSUE TITLE
Add optional admin notification mails

### ISSUE THREAD

**Issue by ivandiazwm** [opensupports/opensupports#16]
The idea of this feature is that a staff can check/uncheck from the admin panel if they want to receive mails when a new ticket is created/answered.
Currently, we are always sending those kind of mails to the regular users, not to staff members. The idea was to avoid bother the staff members with too many mails, but we should allow it if a ticket is created once in a while, so the admin doesn't have to be checking all the time.

**Comment by guillegiu** [comment]
Backend side of this issue is already done.
Frontend pending.
