### ISSUE TITLE
Attach images via Clipboard

### ISSUE THREAD

**Issue by ciph** [opensupports/opensupports#168]
Would love it if you could copy paste images directly into tickets using Snipping tool, Snagit etc..

**Comment by nickbe** [comment]
Excellent idea. I definetely second that!

**Comment by nickbe** [comment]
Image attachment per drag and drop and by copy/paste like in GitHub is a very cool feature. I'm not sure how complex the implementation itself is, but since screenshots are used with every second ticket in our line of work - I say it can be an important feature, once we have it.

**Comment by ivandiazwm** [comment]
This has been released in the v4.3

**Comment by nickbe** [comment]
Great addition to the feature list 👍 Thanks
