### ISSUE TITLE
Download attachment UI

### ISSUE THREAD

**Issue by Kallys** [opensupports/opensupports#17]
Hi !
As a staff member viewing a ticket with an attachment, I can click on it (in order to view/download it), which leads me to a blank page.
In code, checks are made to only allow author or owner of the ticket to download attachment.
And this work, as the author, or if I assign ticket to myself, I can now download attachment.

First, I suggest to return a specific message when trying to download unauthorized attachment (at least a HTTP 403 error).
Secondly, I think staff members could access to attachments even if they are not the owner (sometimes, viewing attachment can help to assign ticket to the right person).

Thanks!

**Comment by ivandiazwm** [comment]
Sure, I think I would be better if allow all staff members to download attachments. A 403 error should be displayed in case of no permission too.

Thanks!

**Comment by ivandiazwm** [comment]
Fixed and released
