### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ivandiazwm** [opensupports/opensupports#172]
Dockerize opensupports to help with dev environment issues.

**Comment by nickbe** [comment]
Forgive me if I object here. 
OpenSupports has alsmost no special dependencies. After for ex. adding an option to use Sqlite you can probably just run it with pure PHP from a usb stick in windows without problems. 

Before trying to dockerize even the most simple of systems like this I‘d rather renove unneccesary dependencies, Although I don‘t think OpenSupports has these at all.

Besides the already known problems with the install routines I think it‘s basically as easy to handle as it gets.

**Comment by paulobezerr** [comment]
Have this project in a docker image will be great because we will be able to deploy this application very fast in k8s or rancher, for example.

And is helpful to manage the installation process, because we we'll have a recipe to install.
I guess that will be better soon than later.

**Comment by nickbe** [comment]
I don‘t see the sense in that when it comes to a system that runs on an USB stick if I so desire. with systems like opensupport it‘s like having a manual to use a spoon. 
A docker image for a system with lots of dependencies is a good thing, but all opensupport needs is a mysql database and PHP. So what‘s the point

**Comment by paulobezerr** [comment]
No system admins have to worry about which version of php, web server, dependencies has to be installed, configure stuff to make things work, etc. 
We can upgrade php version and just do a docker pull and run, with no yum, apt-get, pacman, missed dependencies, broken packages and other problematic and unnecessary things on admins side.
I can put a lot of advantages of containers here, they are good for little systems with few dependencies too. 
If you see what the systems admins can do with Kubernetes, for example, I guess that you can change your mind about it.
In a company with some docker orquestrator, only a few clicks will be necessary to deploy opensupport, as remove, scale, move, etc.

Docker is not only for packaging. ****

**Comment by jocarren** [comment]
I second this request, not supporting docker/kubernetes nowadays is ensuring you are everybody's third choice.

**Comment by nikkilocke** [comment]
You must provide a docker image, or, better, a docker-compose image set (with the SQL server running in a separate image) if you want people to use your system.
I, for one, will not install **anything** on my servers unless it is contained in a docker-compose image set. I am definitely not alone.

**Comment by SkyBehind** [comment]
Couldn't agree more.  I really want to use opensupports over everything else I've seen, but lack of Docker image is a no-go.

**Comment by Teascade** [comment]
I'm just here to third this. Docker is the nowdays, and running opensupports in kubernetes requires a docker image. Not having one pretty much entirely excludes opensupports from any sort of enterprise (or larger than personal) servers, as running it in a cluster instantly becomes much more of a pain than many other options.

**Comment by neobiotics** [comment]
Yes, here too. I was considering using opensupports but no docker-compose is a no no for me.
