### ISSUE TITLE
Router not always working?!

### ISSUE THREAD

**Issue by lukasspy** [opensupports/opensupports#173]
The router seems to be picky, when a link is entered manually in the address bar!

Example: 
When I go to the mainpage (https://subdomain.domain.tld/support ) everything is ok. I click on "Sign Up" and I am correctly rerouted to https://subdomain.domain.tld/support/signup. I can login and I am rerouted correctly to the dashboard, etc.

But when I enter https://subdomain.domain.tld/support/admin into the address bar I get nothing: 404 NOT FOUND. The requested URL was not found on the server (reported by Apache/2.4.18 (Ubuntu))
The same is when verifying the email address by clicking on the "verify-token"-link or even when I am logged in (dashboard) and then open a new tab with the same link to the dashboard. Always 404 NOT FOUND. Same problem with other browsers and on other computers.

What do I have to change? htaccess? Parameter on the server? Or is this an issue with the router?

Thanks in advance!

**Comment by ivandiazwm** [comment]
Hi @lukasspy 
What happens if you directly use `https://subdomain.domain.tld/support/signup` from the address bar, does it works?
If not, it is probably an issue with `.htaccess`, can you place and it is probably related to `AllowOverride` parameter, which causes `.htaccess` files to not be considered.

**Comment by lukasspy** [comment]
Ok .. so I was unaware, that I had to move the `.htaccess` one folder up.

In `https://github.com/opensupports/opensupports/releases/download/v4.1.2/opensupports_v4.1.2.zip` the `.htaccess` is in the api folder.

SOLUTION
I just moved the `.htaccess` one folder up (to the index.php) and now everything is working. 

Is this mentioned anywhere in the docs? If not, it is worth mentioning.
