### ISSUE TITLE
Private notes in ticket

### ISSUE THREAD

**Issue by kittyhackcom** [opensupports/opensupports#174]
Right now, it's not possible to add private notes on tickets (notes that will only be seen by admins and not by the ticket requesters). 

This would be really useful for taking notes or put informations that should not be seen by tickets requesters, like specific details of an intervention for example.

I think it could be implemented as an option to answer a thread, so it can be shown like an answer to a ticket in the interface.

**Comment by nickbe** [comment]
I absolutely agree on that. Having internal notes is probably a must have if you think about it

**Comment by ivandiazwm** [comment]
This looks very interesting and it will be considered for a future version. Thanks for the suggestion!

**Comment by nickbe** [comment]
Since this seems very easy to implement giving a huge advantage when working on a ticket, I think this should be on the top priority list too.

**Comment by ivandiazwm** [comment]
This has been released in the v4.3
