### ISSUE TITLE
Option to create ticket from the admin panel

### ISSUE THREAD

**Issue by kittyhackcom** [opensupports/opensupports#175]
There is no option to create a ticket from the admin panel.

This should be necessary to create one to do a follow up with someone after a phone call or another source (or internal tickets).

**Comment by ivandiazwm** [comment]
Interesting. I'll add it to the list of features. Thanks!

**Comment by nickbe** [comment]
In fact I think this feature is absolutely necessary. Coming from a different ticket system we are creating more tickets internally when developing software for a client than the clients create themselves.

So being able to internally create tickets for a specific someone or department seems really important.

**Comment by ra-uk** [comment]
Dropping use sue to lack of this, other FOSS' have this as standard. Shame as it looks great.

One other thing is there is no template for user CSV upload.
Even just a list of headers would be useful.

**Comment by nickbe** [comment]
Honestly I don't understand what's going on right now.
The 'docker' issues seem to be more important than anything else. Personally I can run OpenSupports under windows with a simple portable UWamp within a minute. Installing it in Debian took some moments later. So what's the point.

Currently there are some real flaws and some really vital features missing. And those are not even big things but absolutely important none the less.

We would have installed and used the system with 50+ users not even counting our own users, but we're now we're also on the verge of dismissing OpenSupports for good. 

I know people are very fond of things like Docker nowadays. But it's completely pointless for a system under construction.

**Comment by nickbe** [comment]
Thanks for your explanation and for your understanding.

#175 surely is one of the most pressing issues for many of us right now. A staff member should never have to enter the client mode at any point.

**Comment by Esager** [comment]
Looking forward to this feature!

**Comment by ivandiazwm** [comment]
This is will be done for next month release https://www.opensupports.com/release-plan-2018/

**Comment by davidgmatthews** [comment]
Looking forward to this feature :)

**Comment by nickbe** [comment]
Has this feature been releases so far?
