### ISSUE TITLE
blank page with nginx with subdomain

### ISSUE THREAD

**Issue by cyberghostbg** [opensupports/opensupports#179]
hello buddies,
i want to use this script but installator give me blank page. I use nginx with subdomain. This is my block config and i dont know where is my mistake, can you help me?

> server {
>     listen 80;
>     listen [::]:80;
>     root /var/www/support/public_html;
>     index index.php index.html index.htm index.nginx-debian.html;
>     server_name support.mysite.com;
> 
> 	location /api {
> 	try_files $uri /api/index.php;
> }
> 
> # Catch-all for rest.
> location / {
> 	try_files $uri /index.php;
> }
> 
> # Handle PHP files.
> location ~ [^/]\.php(/|$) {
> 	fastcgi_split_path_info ^(.+?\.php)(/.*)$;
> 	set $path_info $fastcgi_path_info;
> 	fastcgi_param PATH_INFO $path_info;
> 	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
> 	try_files $fastcgi_script_name =404;
> 	fastcgi_pass 127.0.0.1:9000;
> 	fastcgi_index index.php;
> 	include fastcgi_params;
> }
> 
>     location ~ /\.ht {
>         deny all;
>     }
> }

**Comment by niiayigh** [comment]
Don't know why this issue was closed when it wasn't solved. I found a workaround for this


location /api {
	try_files $uri $uri/ /api/index.php;
}

# Catch-all for rest.
location / {
	try_files $uri $uri/ /index.php;
}

# Handle PHP files.
location ~ [^/]\.php(/|$) {
	fastcgi_split_path_info ^(.+?\.php)(/.*)$;
	set $path_info $fastcgi_path_info;
	fastcgi_param PATH_INFO $path_info;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	try_files $fastcgi_script_name =404;

	fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
	fastcgi_index index.php;
	include fastcgi_params;
}
