### ISSUE TITLE
Unable to create departements and others in Chinese and other languages. Also, suggest to make a locale folder instead of putting everything in main.js

### ISSUE THREAD

**Issue by ksgithubapp** [opensupports/opensupports#182]
Unable to create departements and others in Chinese and other languages. Also, suggest to make a locale folder instead of putting everything in main.js

**Comment by ksgithubapp** [comment]
The languages in the system are ridiculously translated.

**Comment by mredigonda** [comment]
Hi, the issue with non-alphanumeric names for departments is reported here #70 and here #83, it will be fixed for a future release.
About the languages, sorry, not all of them are finished yet, but some amazing guys (#170, #118, #162, #50, #10 are just some examples) are already making contributions with what they know, so feel free to contribute if you want!
As of the problem with main.js, I agree that having a main.js too bloated is a clear efficiency problem and this is one of the things we are discussing with the team. One of the ideas is to remove JQuery.
Thank you.
