### ISSUE TITLE
blank install

### ISSUE THREAD

**Issue by FroztIkon** [opensupports/opensupports#22]
Downloaded release directly to server, unzip and changed ownership of all files.
Ubuntu 16.04
Apache 2.4+
PHP 5.6.30
MySQL 5.7.18
Database client version: libmysql - mysqlnd 5.0.11
`
 PHP Warning:  require_once(vendor/autoload.php): failed to open stream: Permission denied in /home/admin/web/public_html/api/index.php on line 3, referer: 
PHP Stack trace:, referer: 
PHP   1. {main}() /home/admin/web//public_html/api/index.php:0, referer: 
`

**Comment by fedexyz** [comment]
Try chown -R www-data:www-data to the folder

**Comment by FroztIkon** [comment]
Already tried that. All files and folders are owned by appropriate
user/group

**Comment by FroztIkon** [comment]
While it was very slow to load the install page, my fix:

index.php line 23:
from
`apiRoot = '<?=$url ?>/api';`
to
`apiRoot = '<?=$url ?>api';`

**Comment by indiecore-fm** [comment]
Same exact issue here. Editing line 23 will show installer, but there is something wrong with main.js. It causes my browser to lag and next does not work.

**Comment by Kallys** [comment]
Got the same issue when trying to configure opensupports in sub-domain with apache.
In index.php, $_SERVER['PHP_SELF'] contains "/index.php" and dirname($_SERVER['PHP_SELF']) returns "/". But then code assumes there is no trailing slash in those variables. I guess test where given with PHP_SELF returning a folder/file schema.

I'll make a PR but for now, quick fix (both blank install and main.js infinite looping):
Replace following lines:
```
<?php
    $url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']);
    $path = dirname($_SERVER['PHP_SELF']);
?>
```

By thoses ones:
```
<?php
    $path = rtrim(dirname($_SERVER['PHP_SELF']), '/');
    $url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $path;
?>
```

And keep other lines unchanged (especially the `apiRoot = '<?=$url ?>/api';` part).

**Comment by creativefx** [comment]
I tryed both options but nothing...

https://help.creativefx.de/

**Comment by Kallys** [comment]
Did you try my solution ?

Your index.html returns:
```<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
    
        <title>OpenSupports</title>
    
        <link rel="stylesheet" href="https://help.creativefx.de//css/main.css">
        <link rel="icon" type="image/x-icon" href="https://help.creativefx.de//images/icon.png">
    </head>
    <body>
        <div id="app"></div>
        
        <script>
            root = "https://help.creativefx.de/";
            apiRoot = 'https://help.creativefx.de/api';
            globalIndexPath = "/";
        </script>
        <script src="https://help.creativefx.de//js/main.js"></script>
    </body>
</html>```

instead of:
```<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
    
        <title>OpenSupports</title>
    
        <link rel="stylesheet" href="https://help.creativefx.de/css/main.css">
        <link rel="icon" type="image/x-icon" href="https://help.creativefx.de/images/icon.png">
    </head>
    <body>
        <div id="app"></div>
        
        <script>
            root = "https://help.creativefx.de";
            apiRoot = 'https://help.creativefx.de/api';
            globalIndexPath = "";
        </script>
        <script src="https://help.creativefx.de/js/main.js"></script>
    </body>
</html>```

**Comment by creativefx** [comment]
idk why but today it works...

**Comment by FroztIkon** [comment]
ok, so just like another script I was installing for a client, if there's an index.html file, it can cause issues. Don't ask why, removal of the .html file + kally's change worked. But it didn't redirect to the admin panel after install, had to figure out it's location on my own.
