### ISSUE TITLE
My tickets display closed tickets

### ISSUE THREAD

**Issue by Nononwmana** [opensupports/opensupports#225]
Hi!
Closed tickets are still visible in my tickets, and i see no possibility to show only open ones.
Also, they are not displayed by date (new one should be at top)

**Comment by mredigonda** [comment]
Thanking you for taking the time to create those mockups. I agree we should be able to differentiate between opened and closed tickets.

**Comment by ivandiazwm** [comment]
This feature has been released with a `Show closed tickets` checkbox. However, more filters will be added in a future version.
