### ISSUE TITLE
Blank page at the installation (Ubuntu 16.04 and Apache2)

### ISSUE THREAD

**Issue by antvet** [opensupports/opensupports#239]
So like a lot of people here, I have [a blank page](https://zupimages.net/up/18/28/as4r.png) when I try to install OpenSupport. Here are [the errors in my console](https://zupimages.net/up/18/28/9ptw.png) and in [the network connection](https://zupimages.net/up/18/28/dy0h.png). The problem is the same if I use Firefox or MS Edge.
I'm trying to run this on Ubuntu 16.04 with Apache 2.4.18, MySQL 5.7.22 and PHP 5.6.36. I didn't set "AllowOverride All" because it gave me a 500 error so I left it by default on "None". My PDO are enabled:
```
user@computer:/var/www$ php -i | grep PDO
PDO
PDO support => enabled
PDO drivers => mysql
PDO Driver for MySQL => enabled
```
I don't know what to do actually... Any advice?

Thanks.

**Comment by ivandiazwm** [comment]
Ok, since the 404 errors are on the api paths it could mean one of two things:
1. The path generated could be wrong: check the html source code in chrome (`View page source`). `apiRoot` on line 19 should have the path to be something like `http://yourwebsite.com/your-opensupports-path/api` (you can check how it should look on `dev1.opensupports.com`)

2. Not having `AllowOvereride All` could be the problem, try by adding it to the opensupports folder and check the error log. Does the previous url load? Are the errors shown only on api POST paths?

Software version should work. I'm going to check if there's any issue with PHP 5.6.

**Comment by antvet** [comment]
Thank you for your answer. For the first thing, [everything seems to be good](https://zupimages.net/up/18/28/gms9.png). For the second, [here the error 500](https://zupimages.net/up/18/28/advs.png) and the apache logs when I try to load the page on my pc (I just replaced my IP by XX.X.X.XXX):
`XX.X.X.XXX - - [10/Jul/2018:09:04:10 +0200] "GET / HTTP/1.1" 500 799 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
XX.X.X.XXX - - [10/Jul/2018:09:04:10 +0200] "GET /favicon.ico HTTP/1.1" 500 799 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
XX.X.X.XXX - - [10/Jul/2018:09:04:10 +0200] "GET /favicon.ico HTTP/1.1" 500 799 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"`

**Comment by antvet** [comment]
@ivandiazwm any idea?

**Comment by antvet** [comment]
It worked @InsolentLlama. Thank you!

**Comment by ivandiazwm** [comment]
Hi @damiankw . The issue seems to be with the frontend `.js` file, please replaces `js/main.js` with [this development version](https://s3.amazonaws.com/opensupports/main.js) and reload it (`Ctrl+Shift+R`) so you can have a more detailed error. Please post it here after it.

**Comment by damiankw** [comment]
Hey @ivandiazwm, thanks for the prompt response! Here's the error log from console now:

```
DevTools failed to parse SourceMap: http://support.domain.org/sass
lowPriorityWarning.js:38 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ lowPriorityWarning.js:38
lowPriorityWarning @ lowPriorityWarning.js:57
get @ React.js:98
488.react @ index.js:27
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ App.js:4
901.app-components/modal-container @ App.js:142
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
902.app/App @ Routes.js:2
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ index.js:6
1011.actions/config-actions @ index.js:42
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
lowPriorityWarning.js:38 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
printWarning @ lowPriorityWarning.js:38
lowPriorityWarning @ lowPriorityWarning.js:57
get @ React.js:106
createSideEffect @ index.js:21
488.react @ index.js:15
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ App.js:4
901.app-components/modal-container @ App.js:142
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
902.app/App @ Routes.js:2
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ index.js:6
1011.actions/config-actions @ index.js:42
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
factoryWithTypeCheckers.js:21 Warning: Invalid argument supplied to oneOfType, expected an instance of array.
printWarning @ factoryWithTypeCheckers.js:21
createUnionTypeChecker @ factoryWithTypeCheckers.js:335
(anonymous) @ form-field.js:19
969.classnames @ form-field.js:13
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
970.classnames @ form.js:6
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
890.classnames @ password-recovery.js:5
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
948.actions/session-actions @ main-home-page-login-widget.js:10
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
950.app/main/main-home/main-home-page-login-widget @ main-home-page.js:5
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
902.app/App @ Routes.js:8
s @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ index.js:6
1011.actions/config-actions @ index.js:42
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
config-reducer.js:52 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at onInitConfigs (config-reducer.js:52)
    at reducer.js:8
    at combination (combineReducers.js:133)
    at dispatch (createStore.js:178)
    at index.js:35
    at dispatch (applyMiddleware.js:45)
    at handleFulfill (index.js:134)
```

**Comment by nickbe** [comment]
Same problem here - latest version. 
The Installation page stay empty:

![grafik](https://user-images.githubusercontent.com/10890765/49335165-996bd980-f5e8-11e8-917a-f05fca81f27e.png)

**Comment by ivandiazwm** [comment]
@damiankw I've identified the issue with the release and fixed it, there was an error during our release process. Please download the package aging from our website. It should be working now.
@nickbe Your issue seems to be different from the one we found (api is not working?). However, please download the package aging to see if it get's fixed.

**Comment by damiankw** [comment]
Thanks @ivandiazwm! The installer now loads, I'll test it all out a little later to ensure she's all running perfect :D

**Comment by nickbe** [comment]
I've tried this version: https://s3.amazonaws.com/opensupports/main.js
I suppose that this is the patched version. But still I get nothing.

**Comment by ivandiazwm** [comment]
@nickbe no, that's not the patches version, just download this one https://github.com/opensupports/opensupports/releases/download/v4.3.2/opensupports_v4.3.2.zip

**Comment by nickbe** [comment]
Ok done. Still nothing:
INVALID REQUEST to: /system/installation-done main.js:60:11088
undefined main.js:60:11126
INVALID REQUEST to: /system/get-settings main.js:60:11088
undefined main.js:60:11126
INVALID REQUEST to: /user/check-session main.js:60:11088
undefined main.js:60:11126
Error: 
main.js:35:19666

**Comment by nickbe** [comment]
@ivandiazwm : How do you delete a ticket now?

**Comment by ivandiazwm** [comment]
@nickbe You have "Delete ticket" button on the response area
![screenshot 3](https://user-images.githubusercontent.com/6447076/49345048-4d5b7c00-f65e-11e8-9c65-2e983d10d10b.png)

**Comment by nickbe** [comment]
Found it this second. Took several minutes to find out that this only works if there's no one assigned to that ticket which seems odd.

**Comment by nickbe** [comment]
Anyway the logic seems reasonable now.
Remove the assigned user and then delete the ticket - fine by me :)

Maybe you should show the delete-button anyway and throw an error instead. That way the user would know why he can't delete the ticket.
