### ISSUE TITLE
How to Run the script with php 4.1.3.php

### ISSUE THREAD

**Issue by b4allb4u** [opensupports/opensupports#240]
Hi Dev Team 

Greetings of the day! 
I would like to inform you that, I have uploaded upgrade version files of open supports to my server using with FTP client. Pls advice me on how to RUN the script with php 4.1.3.php

Regards
B4ALLB4U

**Comment by ivandiazwm** [comment]
Hi @b4allb4u, you can enter to your server's console using SSH.
Once you are on your OpenSupports folder, execute the following commands:
1. `cd version_upgrades/4.1.3` to enter the update folder
2. `php 4.1.3.php` to run the script should work.

Another way could be going to 
`http://yourwebsite.com/your-opensupports-path/version_upgrades/4.1.3.php` on the browser  .

Execute it only once.
It should show no output if everything is OK. Remember deleting `version_upgrades` folder after that.

**Comment by b4allb4u** [comment]
Hi @ivandiazwm , thanks a lot for your valuable support and quick response. Now I have successfully updated our opensupports ticket system to stable version 4.1.3.

Regards

B4ALLB4U
