### ISSUE TITLE
Work with out an account

### ISSUE THREAD

**Issue by Mayer-Studios** [opensupports/opensupports#241]
The option to not require an account to do things would be greatly appreciated.

**Comment by madfunny** [comment]
For the client?

**Comment by Mayer-Studios** [comment]
That is correct. To view the knowledge base, and submit a ticket, you have to have an account, which some users may not want to have

**Comment by ivandiazwm** [comment]
@Mayer-Studios You can disable the user system by going to `Settings -> Advanced Settings` on the admin panel and set `Use user system for customers` and `Enable user registration` both on `Off`.

In that way, customers are not required to create an user to create tickets or view the articles.
