### ISSUE TITLE
Feature suggestion - custom fields

### ISSUE THREAD

**Issue by svoop** [opensupports/opensupports#263]
It would be very helpful to allow custom fields for tickets e.g. to ask for a mobile phone number.

**Comment by alexrait** [comment]
I would like to see that too.
Structured form, asking for phone, version, company e.t.c

**Comment by mredigonda** [comment]
We really want to add this feature, but sadly [it's not planned for releases in the near future](https://github.com/opensupports/opensupports/projects/1). As you can see, there are many other important features to add before adding custom fields, but it's definitely something we will work on in the future.
Thanks for the suggestion!

**Comment by nickbe** [comment]
I agree. For example tags are much more important in my opinion

**Comment by nickbe** [comment]
I suppose this would also resolve my suggestion for an "organisation" field.
How do you plan to implement this? per department or globally?

**Comment by ivandiazwm** [comment]
@nickbe the implementation is currently done as additional fields for users.

**Comment by lyrics1988123** [comment]
these custom fields are not shown on the page while creating a ticket, only if user registration is activated.. w use guest-tickets and there are no custom fields.. could you please check this? i dont think, that custom fields only should work with user registration..

thanks!

**Comment by alexrait** [comment]
> these custom fields are not shown on the page while creating a ticket, only if user registration is activated.. w use guest-tickets and there are no custom fields.. could you please check this? i dont think, that custom fields only should work with user registration..
> 
> thanks!

Exactly, same user can register for many issue types / products.
