### ISSUE TITLE
SMTP not working v4.1.3

### ISSUE THREAD

**Issue by bitcoinshirt** [opensupports/opensupports#264]
Hi,

I am using v4.1.3 via Softaculous.
I've set up my STMP settings but when an email is sent to the email I've defined, nothing happens and the ticket is not created.
My hosting support had a look into SMTP settings and verified it's correctly setup.

![screen shot 2018-07-31 at 22 26 25](https://user-images.githubusercontent.com/36959754/43485200-d2a8e780-9510-11e8-9375-b53e46577c7d.png)

Am I just missing the point that a ticket should be created when an email is sent to a defined support email?

Are there any issues with SMTP so far in this version?

**Comment by ivandiazwm** [comment]
Hi @bitcoinshirt , our system doesn't currently have the capability of creating tickets from an email, but we have planned to implement it on v4.4 https://github.com/opensupports/opensupports/issues/64. SMTP configuration is just for sending email notifications.
