### ISSUE TITLE
System not allowing to modify the Email Templates.

### ISSUE THREAD

**Issue by b4allb4u** [opensupports/opensupports#267]
Hi Dev Team
Greetings of the Day!
We would like to inform you that. Whenever we changed the Email Templets to our needs then the system has failed to send the email notification in the original format. 

Pls look into this matter and allow us to change the email templets to our needs. 

B4ALLB4U
[Original Email Template.pdf](https://github.com/opensupports/opensupports/files/2259320/Original.Email.Template.pdf)

**Comment by ivandiazwm** [comment]
Thanks for reporting it. We will check it out.

**Comment by b4allb4u** [comment]
Hello Dev Team 
Any update on this issue?

Regards

B4ALLB4U

**Comment by ivandiazwm** [comment]
Email templates have been refactored and released.

**Comment by b4allb4u** [comment]
@ivandiazwm thanks a lot for your support.

**Comment by b4allb4u** [comment]
@ivandiazwm I have successfully updated my opensupports to the latest stable version 4.3.2. In the latest version, Existing Email templates are in invisible mode.

![emails](https://user-images.githubusercontent.com/24243794/49280726-e77dc180-f4b0-11e8-8466-6e3e19cd2014.png)

Pls, look into this matter and resolve the issue.

Thanks in Adv
B4ALLB4U

**Comment by ivandiazwm** [comment]
@b4allb4u That's very strange. It should too long in showing the list. It haven't been able to reproduce it in our development environments. Have you run the `4.3.2.php` script?
Could you enable logs `showLogs = true` in `index.php` file and show what is responded by `/system/get-mail-template-list` request on the browser console?

**Comment by b4allb4u** [comment]
@ivandiazwm Sometimes simple things are also created magical movements, I just enabled the showLogs = true. within a sec, everything is working fine. four letters (TRUE) did really magic on my support system. I think there is no interrelation between these two fields. But Now my system is working awesome. 

Thanks a lot for your valuable guidelines.   one suggestion from my side, pls add contact field on the signup form.
