### ISSUE TITLE
Comment without assignment

### ISSUE THREAD

**Issue by Kallys** [opensupports/opensupports#27]
I found a little inconsistency between API and client: API allows staff to comment **their** ticket without assigning it while client don't.

Edit: only tested with user system disabled.

**Comment by AntonyAntonio** [comment]
This issue should be fixed in the client side. We should allow that a ticket can be commented without assignment. 
Thanks for reporting this.

**Comment by ivandiazwm** [comment]
After to taking a look to this issue, I found it was an error in the backend code: we were checking if the current logged id matches the author id, but we didn't check that it had to be a regular user, not a staff.

So, if you try to comment a ticket **with a staff that has the same id as the author of the ticket**, the comment will be added. I'm fixing this, owner and author should be the only ones that can comment.
