### ISSUE TITLE
new installation Ubuntu 16.04 shows blank screen

### ISSUE THREAD

**Issue by inaopul** [opensupports/opensupports#279]
Hi Everyone,

I trying to install with self hosted Ubuntu Server 16.04 PHP 7.0 Mysql 5.7 but after unzip opensupport and go throught the website don´t run the wizard just leave the website blank.

**Firefox Console**

request /system/installation-done 
{}
​
<prototype>: Object { … }
main.js:66:26002
{…}
​
adminData: Object { customResponsesLoaded: false, myTicketsLoaded: false, myTicketsError: false, … }
​
articles: Object { retrieved: false, loading: true, errored: false, … }
​
config: Object { initDone: false, installedDone: false, installed: false, … }
​
modal: Object { opened: false, noPadding: false, content: null }
​
routing: Object { locationBeforeTransitions: {…} }
​
session: Object { initDone: false, logged: false, pending: false, … }
​
<prototype>: Object { … }
main.js:66:25011
request /system/get-settings 
Object {  }
main.js:66:26002
{…}
​
adminData: Object { customResponsesLoaded: false, myTicketsLoaded: false, myTicketsError: false, … }
​
articles: Object { retrieved: false, loading: true, errored: false, … }
​
config: Object { initDone: false, installedDone: false, installed: false, … }
​
modal: Object { opened: false, noPadding: false, content: null }
​
routing: Object { locationBeforeTransitions: {…} }
​
session: Object { initDone: false, logged: false, pending: false, … }
​
<prototype>: Object { … }
main.js:66:25011
request /user/check-session 
Object {  }
main.js:66:26002
{…}
​
adminData: Object { customResponsesLoaded: false, myTicketsLoaded: false, myTicketsError: false, … }
​
articles: Object { retrieved: false, loading: true, errored: false, … }
​
config: Object { initDone: false, installedDone: false, installed: false, … }
​
modal: Object { opened: false, noPadding: false, content: null }
​
routing: Object { locationBeforeTransitions: {…} }
​
session: Object { initDone: false, logged: false, pending: false, … }
​
<prototype>: Object { … }
main.js:66:25011
INVALID REQUEST main.js:66:26172
undefined main.js:66:26203
{…}
​
adminData: Object { customResponsesLoaded: false, myTicketsLoaded: false, myTicketsError: false, … }
​
articles: Object { retrieved: false, loading: true, errored: false, … }
​
config: Object { initDone: false, installedDone: false, installed: false, … }
​
modal: Object { opened: false, noPadding: false, content: null }
​
routing: Object { locationBeforeTransitions: {…} }
​
session: Object { initDone: false, logged: false, pending: false, … }
​
<prototype>: Object { … }
main.js:66:25011
INVALID REQUEST main.js:66:26172
undefined main.js:66:26203
{…}
​
adminData: Object { customResponsesLoaded: false, myTicketsLoaded: false, myTicketsError: false, … }
​
articles: Object { retrieved: false, loading: true, errored: false, … }
​
config: Object { initDone: false, installedDone: false, installed: false, … }
​
modal: Object { opened: false, noPadding: false, content: null }
​
routing: Object { locationBeforeTransitions: {…} }
​
session: Object { initDone: false, logged: false, pending: false, … }
​
<prototype>: Object { … }
main.js:66:25011
INVALID REQUEST main.js:66:26172
undefined main.js:66:26203
Error: 
main.js:42:18653

**Chrome Console**

request /system/installation-done {}
main.js:66 {session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, …}adminData: {customResponses: Array(0), customResponsesLoaded: false, myTickets: Array(0), myTicketsLoaded: false, myTicketsError: false, …}articles: {retrieved: false, loading: true, errored: false, topics: Array(0)}config: {language: null, initDone: false, installedDone: false, installed: false}modal: {opened: false, noPadding: false, content: null}routing: {locationBeforeTransitions: {…}}session: {initDone: false, logged: false, pending: false, failed: false, verify: null}__proto__: Object
main.js:66 request /system/get-settings {}
main.js:66 {session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, …}adminData: {customResponses: Array(0), customResponsesLoaded: false, myTickets: Array(0), myTicketsLoaded: false, myTicketsError: false, …}articles: {retrieved: false, loading: true, errored: false, topics: Array(0)}config: {language: null, initDone: false, installedDone: false, installed: false}modal: {opened: false, noPadding: false, content: null}routing: {locationBeforeTransitions: {…}}session: {initDone: false, logged: false, pending: false, failed: false, verify: null}__proto__: Object
main.js:66 request /user/check-session {}
main.js:66 {session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, …}adminData: {customResponses: Array(0), customResponsesLoaded: false, myTickets: Array(0), myTicketsLoaded: false, myTicketsError: false, …}articles: {retrieved: false, loading: true, errored: false, topics: Array(0)}config: {language: null, initDone: false, installedDone: false, installed: false}modal: {opened: false, noPadding: false, content: null}routing: {locationBeforeTransitions: {…}}session: {initDone: false, logged: false, pending: false, failed: false, verify: null}__proto__: Object
main.js:1 POST http://172.16.0.252/support/api/system/installation-done 404 (Not Found)
(anonymous) @ main.js:1
t.exports @ main.js:1
t.exports @ main.js:1
Promise.then (async)
r.request @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:67
post @ main.js:67
(anonymous) @ main.js:66
call @ main.js:66
checkInstallation @ main.js:44
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:66 INVALID REQUEST
main.js:66 undefined
main.js:66 {session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, …}adminData: {customResponses: Array(0), customResponsesLoaded: false, myTickets: Array(0), myTicketsLoaded: false, myTicketsError: false, …}articles: {retrieved: false, loading: true, errored: false, topics: Array(0)}config: {language: null, initDone: false, installedDone: false, installed: false}modal: {opened: false, noPadding: false, content: null}routing: {locationBeforeTransitions: {…}}session: {initDone: false, logged: false, pending: false, failed: false, verify: null}__proto__: Object
main.js:1 POST http://172.16.0.252/support/api/system/get-settings 404 (Not Found)
(anonymous) @ main.js:1
t.exports @ main.js:1
t.exports @ main.js:1
Promise.then (async)
r.request @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:67
post @ main.js:67
(anonymous) @ main.js:66
call @ main.js:66
init @ main.js:44
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:66 INVALID REQUEST
main.js:66 undefined
main.js:66 {session: {…}, config: {…}, modal: {…}, articles: {…}, adminData: {…}, …}adminData: {customResponses: Array(0), customResponsesLoaded: false, myTickets: Array(0), myTicketsLoaded: false, myTicketsError: false, …}articles: {retrieved: false, loading: true, errored: false, topics: Array(0)}config: {language: null, initDone: false, installedDone: false, installed: false}modal: {opened: false, noPadding: false, content: null}routing: {locationBeforeTransitions: {…}}session: {initDone: false, logged: false, pending: false, failed: false, verify: null}__proto__: Object
main.js:1 POST http://172.16.0.252/support/api/user/check-session 404 (Not Found)
(anonymous) @ main.js:1
t.exports @ main.js:1
t.exports @ main.js:1
Promise.then (async)
r.request @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:67
post @ main.js:67
(anonymous) @ main.js:66
call @ main.js:66
payload @ main.js:44
initSession @ main.js:44
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:66 INVALID REQUEST
main.js:66 undefined
main.js:42 Uncaught (in promise) Error
    at v (main.js:42)
v @ main.js:42
Promise.then (async)
(anonymous) @ main.js:42
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:42 Uncaught (in promise) Error
    at v (main.js:42)
v @ main.js:42
Promise.then (async)
(anonymous) @ main.js:42
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
(index):1 Uncaught (in promise) {status: "fail", message: "Internal server error"}message: "Internal server error"status: "fail"__proto__: Object
Promise.then (async)
payload @ main.js:44
initSession @ main.js:44
(anonymous) @ main.js:66
1020.actions/config-actions @ main.js:66
o @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1

**Comment by ivandiazwm** [comment]
It looks like `.htaccess` is not working. Could you please check if you have `AllowOverride All` active on your apache configuration? https://github.com/opensupports/opensupports/issues/239#issuecomment-404135398

**Comment by inaopul** [comment]
that was right, I config correctly the rewrite function and it worked, but I have problem with email service because it don't send any email, please how I can check thsis problem?
