### ISSUE TITLE
File: /api/config.php | Not writable & Folder: /api/files	 Not writable

### ISSUE THREAD

**Issue by AMG-90** [opensupports/opensupports#281]
my firts issue was - A blank screnn while installing on Apache based on CentOS 7, but i was passing that thanks to every one here who gave me a good solution for that!!! so firts thaks , 

now i am trying to install and i am stuck at 

Requirement | Value
-- | --
PHP Version | 7.2.8
PDO Module | Available
File: /api/config.php | Not writable
Folder: /api/files | Not writable

what should i do to make it writable ??
Thanks everyone in advanced 
 
![image](https://user-images.githubusercontent.com/42431537/44192926-e4e1a100-a139-11e8-9c25-86f3f9cca243.png)

**Comment by AMG-90** [comment]
i tried 2/3 things for fixing that , but still it didnt worked for me 
sudo chown -R apache:apach /var/www/html/opensupports1/api/config.php
i did that with 777 as well but noting changed 
same about files 
sudo chown -R apache:apache /var/www/html/opensupports1/api/files/

**Comment by ivandiazwm** [comment]
We use [is_writable](https://github.com/opensupports/opensupports/blob/master/server/controllers/system/check-requirements.php#L50) function from PHP to check if a file is writable or not.

It could be caused by SELinux not allowing write access, can you check it?
https://stackoverflow.com/a/45071223
https://www.serverlab.ca/tutorials/linux/web-servers-linux/configuring-selinux-policies-for-apache-web-servers/

**Comment by AMG-90** [comment]
thanks a lot it happend duh Selinux
I was disabling the selinuix and i path that issue

**Comment by sysadt** [comment]
Hello,
can you please tell me what you did with SELinux?
I have the exact same problem as you explained at the top.

**Comment by Manishfoodtechs** [comment]
I solved this error on ubuntu as following :

 cd to api folder
- sudo chmod a+rwx config.php
namei -l config.php

-sudo chmod a+rwx files
namei -l config.php

Refresh Step 2 :)

**Comment by paulkiragu621** [comment]
> I solved this error on ubuntu as following :
> 
> cd to api folder
> 
> * sudo chmod a+rwx config.php
>   namei -l config.php
> 
> -sudo chmod a+rwx files namei -l config.php
> 
> Refresh Step 2 :)

This worked on Linux mint, thanks!
