### ISSUE TITLE
An error occurred while trying to update settings: Could not connect to database (?).

### ISSUE THREAD

**Issue by AMG-90** [opensupports/opensupports#282]
i just passed Step 2 and strated step 3 i remmber all the  Parametes that requird but still 
i am getting error

An error occurred while trying to update settings: Could not connect to database (?).

any one got any idea what to do here ?

**Comment by ivandiazwm** [comment]
It shouldn't happen. You can clear the content of `api/config.php` (make it a an empty file) and try installation aging.

Let me know if it helps.

**Comment by AMG-90** [comment]
works !! thanks
