### ISSUE TITLE
Staff members cannot update their passwords

### ISSUE THREAD

**Issue by TheKeiki** [opensupports/opensupports#288]
Hello.

We have been testing your system (v.4.2.0) and found it very easy to use and comfortable for our clients, however we have found 1 error and we have a suggestion:

(BUG) No member of staff can update his password if they dont have ticket level 3 enabled, if they try to change the password with level 1 or 2 the system returns an error.

(Suggestion)- Please add a field in the client form where they can put their company name, we manage several companies and in this way it would be easier to find the solution to their problems.

**Comment by ivandiazwm** [comment]
Thanks for reporting this issue. It needs to be fixed

**Comment by mredigonda** [comment]
This will be published in the next release, thanks for reporting!

**Comment by TheKeiki** [comment]
No problem, keep the good work!
