### ISSUE TITLE
Login form does not work in Safari

### ISSUE THREAD

**Issue by anggras** [opensupports/opensupports#297]
When using Safari desktop web browser, user is unable to key in all inputs (email, password and remember me checkbox)

**Comment by nickbe** [comment]
Same here, but with iOS/iPhone X. The fields cannot be clicked or entered at all.

**Comment by instanttim** [comment]
This has to do with the "flipped" password recovery view. Even though it's not visible, it's "on top" and steals the mouse clicks with respect to focusing on the fields. You can "tab" into the visible fields (but can't focus the buttons unless you have full keyboard nav turned on.)

Verified by inspecting the elements and deleting the password recovery DIV. Haven't looked at the CSS to see if i can just fix the layering yet.

**Comment by nickbe** [comment]
I suggest to remove the flip effect completely. It does not make any sense and it's really important to be able to use mobiles when you're a technicial constantly on the road.

**Comment by ChronicledMonocle** [comment]
Also have this issue and unfortunately, its a dealbreaker for me, as the person that's going to be using it the most works off an iOS device.
