### ISSUE TITLE
Manually creating new user

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#300]
Is it still on the agenda to give the admin the ability to create a new user manually. In my case I don't want the users to register themselves, but to create several accounts and let the system send them randomly created passwords on creation.

**Comment by mredigonda** [comment]
I'm glad to say this is already under development. You will see it working soon.

**Comment by nickbe** [comment]
*Sigh*  😄  thanks

**Comment by nickbe** [comment]
I suppose this was added in th recent release.
