### ISSUE TITLE
Disable frontend registration

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#308]
I want that the users account are created automatically by using the endpoints and disable the interface.
There is a way without edit the software manually?

**Comment by Mte90** [comment]
Looking at https://github.com/opensupports/opensupports/blob/e8c50339c1d999de5f6f9d22a1d8f3ff7d416a8c/client/src/app/main/main-layout-header.js#L35 seems that the option to disable registration hide that button but the api will still work?

**Comment by Mte90** [comment]
Looking at https://github.com/opensupports/opensupports/blob/master/server/controllers/user/signup.php#L82 seems that disable also the api that settings, so right now is not possible.

**Comment by Mte90** [comment]
A workaround for that ```.main-layout-header__login-links .button:nth-child(2) {
  display: none;
}```

But I don't like it so much, right now require to hack the js bundle and recompile everything to remove it manually, with css was easy to fix but is not something affordable for a long time.

**Comment by ivandiazwm** [comment]
Hi @Mte90 I think that what you're looking for is the `Registration API Keys`.
It's a feature available on `Admin Panel`->`Settings`->`Advanced Settings`.
When you disable user registration, you can still create users if you also send one of the api keys you created in the admin dashboard in a request to the path `/user/signup`.
This allows you to handle user registration from another application.

Please take a look to the documentation:
https://www.opensupports.com/apidoc/#api-User-Sign_up

Let me know if that is what you were looking for.

**Comment by Mte90** [comment]
Thanks!
