### ISSUE TITLE
SMTP Sugggestion regarding settings

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#312]
I found out that SMTP worked when I use port 587 instead of 25 (Port 25 is forbidden).
By selecting 587 the PHPMailer automatically uses the right encryption mode. But this should be mentioned in the settings somehow. Also if the port derivates from 587 then there's no way to set the encryption mode seperately

**Comment by nickbe** [comment]
Solved due to new configuration options. Closed.

**Comment by Karljklung** [comment]
Hey! How did you do this?

I tried to add this into the code:

`$mail->SMTPSecure = "ssl";`

Did not work well...

**Comment by nickbe** [comment]
Please check out the wiki entry for mail configuration options. This should explain everything.
