### ISSUE TITLE
Submit Buttons Just Rotatitng

### ISSUE THREAD

**Issue by UniqueJoy** [opensupports/opensupports#314]
**1)when a user create a ticket and submit it the button just animating ,not responding but in database the info is added.

2) after registration page submit also the button animating does not redirect or shows any messeges.. but in database new user gets added. , also smtp info given correctly but does not receiving email

3)similarly when admin replies to ticket the button animating and added to db but not stopping animation and not doing further step.. and
shows 

An error occurred while trying to add the comment... but in database it is added**

**Comment by hasteroid** [comment]
same issue here, but users are not in DB aftwer trying to add them. There's no response in console and lasts more than 25 seconds only to get the message "user already exists". Ovbiously there's any user that exists with this e-mail. In fact there's only admin user.
I'll try to uninstall and re-install opensupports to see what happen.

**Comment by hasteroid** [comment]
yup, issue solved, it's working like a charm (after uninstall - install - edit DB prime numbers)
