### ISSUE TITLE
Profile Photo Links to 404

### ISSUE THREAD

**Issue by TrustyTristan** [opensupports/opensupports#317]
I have an issue where the profile picture links to a 404.

http://my.url.com.au/api/system/download?file=898139_picture-file.jpg

The file uploads and is located in /api/files/898139_picture-file.jpg

I'm using nginx, and I suspect that I don't have the proper redirect or something.

`server {
        listen 80;
        listen [::]:80;
        root /var/www/my.url.com.au/html/;
        index index.php index.html index.htm;
        server_name my.url.com.au;

        # Special API location block.
        location /api {
                try_files $uri $uri/ /api/index.php;
        }

        # Catch-all for rest.
        location / {
                try_files $uri $uri/ /index.php;
        }

        # Handle PHP files.
        location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                set $path_info $fastcgi_path_info;
                fastcgi_param PATH_INFO $path_info;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                try_files $fastcgi_script_name =404;

                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }

}`

**Comment by tarasian666** [comment]
Same problem

https://github.com/opensupports/opensupports/issues/54#issuecomment-364045748
