### ISSUE TITLE
tickets created via API behaving strangely

### ISSUE THREAD

**Issue by instanttim** [opensupports/opensupports#320]
I created a couple of tickets via the API, and i can't reassign or edit some of the fields for these tickets. I can't figure out why they would be less editable than anything else though.

Here's a screenshot of the four tickets i have, the first two made in the web UI, the second two made via the API.

<img width="1327" alt="screen shot 2018-09-27 at 9 05 12 pm" src="https://user-images.githubusercontent.com/6156678/46187654-7e53b500-c299-11e8-8144-9b2e1a8e5b2e.png">

**Comment by ivandiazwm** [comment]
Currently, a staff needs to have the ticket assigned to make modifications (you've to be either the owner or the author).
This may change in future versions, but that's how it should work at least for now.

**Comment by instanttim** [comment]
But as an admin staff member, i should be able to re-assign the issue to me. I couldn't even do that.

**Comment by ivandiazwm** [comment]
mhm, that doesn't seem right. Does the staff member has the department of the ticket assigned?

**Comment by instanttim** [comment]
Sorry, i moved on to using a different ticketing system as opensupports was too buggy. I can't hep troubleshoot or provide any more info on the matter as i uninstalled it.
