### ISSUE TITLE
When Editing Email Templates the code breaks

### ISSUE THREAD

**Issue by worldofmadness** [opensupports/opensupports#335]
When Editing Email Templates the code breaks

i changed the title and was going to change some things in the default email when i noticed it breaks the emails layout see screen shots of what happens with just changing the title  no code changes.

any way to fix this issue V4.3.0

![chrome_2018-10-12_12-47-12](https://user-images.githubusercontent.com/17691564/46867496-19fa2f00-ce1d-11e8-8d76-ac6494a4716a.png)
![changes the structure](https://user-images.githubusercontent.com/17691564/46867497-19fa2f00-ce1d-11e8-93e1-b82952a2f1c5.png)

**Comment by ivandiazwm** [comment]
Thanks for reproting this. The cause could be. the HTML purifier.

**Comment by johnshumon** [comment]
I have experienced the same. When I changed some default settings in TICKET_CREATED email template it breaks layout in the sent email. Therefore view ticket link in the email doesn't work.

**Comment by gunnerschile** [comment]
I have the same problem , i'm edit  /edit-mail-template.php using your [code](https://github.com/ivandiazwm/opensupports/commit/c3d16376154be9fcdfa727039f32dc6406075f00)  and bug continue

**Comment by worldofmadness** [comment]
the hotfix has just made it worse.

cant even default it back to the one that work its just all broken in emails.

the fixes have not fixed the layout

![chrome_2018-11-10_21-06-45](https://user-images.githubusercontent.com/17691564/48306053-ea7a3780-e52c-11e8-9fb2-185951c6c760.png)


Shows Sad Face

**Comment by ivandiazwm** [comment]
I'm doing a refactor of this feature. Edition will be restricted to header, internal text and image logo.

**Comment by ivandiazwm** [comment]
Email templates have been refactored and released.
