### ISSUE TITLE
Password displayed in the console

### ISSUE THREAD

**Issue by JeDy1111** [opensupports/opensupports#337]
Hello,
At login, the password is displayed in the browser console.
Not good from a security standpoint.
Regards

**Comment by nickbe** [comment]
You're right. Just checked this:
![grafik](https://user-images.githubusercontent.com/10890765/46907635-cc152200-cf15-11e8-836c-bbbb5535f0e1.png)

@ivandiazwm Can we do something about that?

**Comment by ivandiazwm** [comment]
Yes, we're logging all request but we can add an exception.

**Comment by nickbe** [comment]
I just realized that this is because of an error message. So is the message worth investigating?

**Comment by ivandiazwm** [comment]
Logs are not shown by default any more.
To show logs, you've to update the `index.php` javascript global variable:
```
showLogs = true
```

**Comment by JeDy1111** [comment]
Thanks
