### ISSUE TITLE
Filter View [Feature Request]

### ISSUE THREAD

**Issue by versavius** [opensupports/opensupports#347]
So when viewing tickets as an admin either all tickets or my tickets we can view tickets by department but we can not filter anything else.

What we need are a few filter options such as:
Priority (Low/Medium/High)
Status

Staff should be able to select multiple priorities so say can just view medium or high or view all tickets which are open and on hold but ignore tickets which are closed.

![image](https://user-images.githubusercontent.com/11394779/47183508-218b6d80-d320-11e8-807f-7ef6f1ea77bb.png)

This information should be saved as a cookie as most of the time staff will only want to see tickets which are open or other staff that may want to view all tickets.

Currently the view simply shows everything but most of the time staff will only want to view open tickets, being able to filter what is shown by status and priority aids this

**Comment by nickbe** [comment]
There are already multiple posts regarding a tagging system and the option to filter by tags. Also there's already an open|closed filter under construction.

**Comment by mredigonda** [comment]
Yeah, the open/closed filter is already out there, and the tagging system will also need filtering functionality.
I'm thinking of a "filters" button that will display all of the criteria by which you want to filter tickets (open/closed, priorities, tags, etc.).

**Comment by mredigonda** [comment]
This is finally being worked on by @guillegiu and it will be live soon.
