### ISSUE TITLE
Commentnig on tickets in my department is not possible

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#358]
If user A created a ticket and assigned it to himself, and both me and him have access to the same department as defined in the ticket - then it should also be possible that I write comments in the ticket (In this case I'm his supervisor). But it seems that I cannot do this which is rather odd. Seems like a bug? Could you fix this?

**Comment by nickbe** [comment]
Any news regarding this issue?

**Comment by ivandiazwm** [comment]
Currently, you can add comments to a ticket only if you're the author or the owner.

**Comment by nickbe** [comment]
I know, but that's a problem if you're working in a team.  Usually we need to cooperate with other staff members and I think this is quite common for a support platforms. I think it would be better if you let the members of a department comment in tickets belonging to the same department

**Comment by nickbe** [comment]
Commenting in departments tickets would solve the problem easily.
So duplicate of #396
