### ISSUE TITLE
How to add a link Button

### ISSUE THREAD

**Issue by b4allb4u** [opensupports/opensupports#360]
Hello Dev Team 
Greetings of the Day!
Please advice me on how to add another button i.e Home after Login, Signup. I want to add a button like Home. If a customer clicks on this button, the system has to redirect the customer to our main website.

Pls advice me 

Thanks in Advance!

**Comment by ivandiazwm** [comment]
1. Clone this repository and go to the version tag you currently have, for example v4.3.0
```
git clone https://github.com/opensupports/opensupports.git
cd opensupports
git fetch origin --tags
git checkout tags/v4.3.0
```
2. Install nodejs and npm.
3. Install dependencies and [run the frontend project](https://github.com/opensupports/opensupports#getting-up-and-running-front-end-client-folder)
```
cd client/
sudo npm install -g gulp
npm install
npm rebuild node-sass
gulp dev
```
4. It should be running on port http://localhost:3000/
5. Edit `main-layout-header.js` component and add your link there
```
<div className="main-layout-header__login-links">
    <a href="your-website-link">my website</a>
```
6. Once you've tested it. Stop `gulp dev` and run `gulp prod --api`
7. Once it's finished, replace the file `js/main.js` in your server with the file `client/build/js/main.js` on your machine.

You have to know a bit of React/SAAS if you want to make more customization.

Keep in mind that `main.js` will be replaced with every new release version, so these changes will be reverted when you upgrade to a new version. You can to have a a special branch on your fork with the changes you make and then merge the new releases into it. This way you can keep up with the latest version and maintain your customization.
