### ISSUE TITLE
No Installation possible

### ISSUE THREAD

**Issue by solariz** [opensupports/opensupports#37]
Everytime I walk through the initial Setup wizzard everything is fine. But if I later want to login to my just now created account system keeps telling me "invalid password" if I try to recover it tells "email does not exists"

A close look into the DB show the existing user with email and a hashed password, also others tables were populated by the installation script.

Any clue?

PHP 7.0.18-0ubuntu0.16.04.1
Apache/2.4.18 
Mysql  5.7.18-0

**Comment by solariz** [comment]
Well,

solved - not a "real" Problem. After the installation the Script point you to the main page presenting a Login form. This is the Login for the User, not admin. It would be better to have the installation wizzard point that out clearly that you need to login at /admin not on the mainpage.

Thanks alot!

**Comment by ivandiazwm** [comment]
Yes, you're right. We should point to the admin panel when finishing installed. I will also add a link to the documentation in the admin panel.

**Comment by ivandiazwm** [comment]
Fixed!
