### ISSUE TITLE
Tickets that im working on and that are not closed (filter)

### ISSUE THREAD

**Issue by lyrics1988123** [opensupports/opensupports#371]
hey, 
how can i show every ticket that im working on (that is assigned to me) and that is not closed?
"my ticket" shows also tickets that i have created and tickets that are closed which really isnt that useful.. 

this function is missing hard for a normal workflow..

**Comment by nickbe** [comment]
This is already in the making. See #225 .

**Comment by lyrics1988123** [comment]
my fault! thanks!
