### ISSUE TITLE
Image uploaded from Text Editor is showing more than the ticket container

### ISSUE THREAD

**Issue by taufinaiden** [opensupports/opensupports#375]
After I uploaded an image from the Text Editor, the image displayed in the ticket container is wider than the container.

**Comment by ivandiazwm** [comment]
Thanks for reporting this issue.

This can be fixed by adding the css, (@guillegiu check it doesn't break anything else) 
```
.ticket-event__comment-content img {
    max-width: 100%;
}
```

Also remember that images can be resized when you add them on the ticket/comment form by selecting them.

**Comment by ivandiazwm** [comment]
Fixed
