### ISSUE TITLE
Adding an open/closed column in the ticket tables

### ISSUE THREAD

**Issue by nunolbb** [opensupports/opensupports#380]
should have a column indicating that the call is open or closed.

makes it very difficult because we have to mouse over the link to see if it is open or closed.

**Comment by mredigonda** [comment]
A new column might not be necessary, but there should be a way to clearly represent if the ticket is open or closed in the list of tickets.

**Comment by mredigonda** [comment]
I'm closing this one to discuss about this feature on #424.
