### ISSUE TITLE
Search tickets under all tickets by title/date/priority wise

### ISSUE THREAD

**Issue by sunilpatro08** [opensupports/opensupports#386]
Hi Team,

Could you please help in doing changes to implement for searching tickets under all tickets by title/date/priority wise...

I am able to search for 2 things not more then that.

Thanks

**Comment by mredigonda** [comment]
He might add a filtering system as discussed in #347.

I'm thinking that the search should scan title/content and the filter would narrow down the search based on priorities/dates/tags.
