### ISSUE TITLE
Article with image

### ISSUE THREAD

**Issue by dasimmonds** [opensupports/opensupports#393]
Hi,

There is an odd behavior for creating article with images in them, it is unable to save. Even if use edit and add an image it wont save.

Is there any specific folder permission settings that could be checked? 

I tried looking for information but didnt find any.

Thanks.

**Comment by ivandiazwm** [comment]
It probably could be the image size, which can not be bigger than the settings file size limit.
Could you check if by opening the console (F12, and select console) and then trying to edit gives an `INVALID_FILE` error?

Anyway, the error it's not being displayed and that's an issue. I'll add a fix for it. Thanks for reporting it.

**Comment by dasimmonds** [comment]
Hi Ivan,

I have checked in Cpanel the php ini has sufficient space to upload data.
In the setting tab of opensupports i also put a high value just for this test.

Here is the output of the console.
request /article/add Object { content: "<p>Hi i need to put an image here</…", images: 1, image_0: File, title: "Demo of the Demo", topicId: 1, position: 0 }  main.js:60:21466
Object { status: "fail", message: "LinearCongruentialGenerator: gap mu…", data: null }

**Comment by nickbe** [comment]
@ivandiazwm - Since the UI is Javascript it would seem a better way if you resize the image on the fly when uploading. The max image storage size could be set in a config file.

**Comment by ivandiazwm** [comment]
@dasimmonds What version of OpenSupports are you using?
It looks like the `Hashing` class is generating too big numbers which are not prime.
You can temporarily fix it by changing `ticket-gap` and `file-gap` to 6 digits prime numbers.

If you're using a previous version than v4.3.1, please upgrade.

**Comment by dasimmonds** [comment]
@ivandiazwm  I am on 4.3.1, this is installed on a cpanel hosting PHP 7.2, Mysql 5.7.24.
Changing the numbers to 6 digit prime fixed the issue, able to upload images now.
![settings table2](https://user-images.githubusercontent.com/45100506/48640817-c1691380-ea12-11e8-8430-d5ee9e336e60.png)
Thanks for the help! :1st_place_medal:

**Comment by nickbe** [comment]
> @nickbe max size can be changed in `Admin Panel -> Settings -> System Preferences` (it should say `MB` instead of `KB`, but I've already changed it)
> 
> @dasimmonds It seems your issue is not with file size, but an error trying to generate the number. It the same as #346.
> Could you check if the value on `file-gap` setting on database is a prime number?
> I've however, removed this logic for file uploading and replaced it for one better, so this issue shouldn't happen anymore in the next release.

So, the images are already automatically resized before upload?

**Comment by ivandiazwm** [comment]
@dasimmonds Make sure `ticket-gap` is prime too.
However, this should not be happening in `v4.3.1`. I'll investigate it further to see if can find the issue here.

@nickbe I forgot to address that. No, images are not resized. I'm not sure about this, do you suggest reducing the image quality or the just reduce the dimensions (and consequently the `filesize`) to just what it's needed?

**Comment by nickbe** [comment]
@ivandiazwm - I would suggest only to reduce the dimensions and set the default maximum height/width to a reasonable size like: 1200px. Also I would save all images as JPGs at 85% to 90% quality. Usually the loss at 90% is almost not perceptible at all.

**Comment by nickbe** [comment]
@ivandiazwm - Resizing in the content editor is just the view size but I don't think you can change the actual resultion from there.

**Comment by dasimmonds** [comment]
Thanks for the help and input guys 👍
