### ISSUE TITLE
Console logs must be active only when debug/maintenance mode

### ISSUE THREAD

**Issue by hasteroid** [opensupports/opensupports#404]
The console is full of messages printing what happen on each action. This must be shown only on debug or maintenance mode.

By the other hand i'm getting this message all time, ever after re-installing opensupports:

DevTools failed to parse SourceMap: https://**domain**/sass

**Comment by ivandiazwm** [comment]
Logs are not shown by default any more.
To show logs, you've to update the `index.php` javascript global variable:
```
showLogs = true
```
Please ignore DevTools warning, it has to do with our gulp implementation which we have to check out.
