### ISSUE TITLE
Installing on IIS

### ISSUE THREAD

**Issue by Mboehmlaender** [opensupports/opensupports#426]
Hello everybody!
I'm trying to install OS on my Windows IIS and i have some troubles. When i open the page in my web-browser, the page is blank. In the Browser-Console i get these:

![image](https://user-images.githubusercontent.com/41646409/49991184-91b11b00-ff80-11e8-851d-86b742fb9b01.png)

I imported both .htaccess (root and api) in IIS URL-Rewrite but nothing changes. I also tried all the suggestions from the issues that were already postet here. Is there anything i haven't tried yet?

My web.config looks like this:

![image](https://user-images.githubusercontent.com/41646409/49991401-3b90a780-ff81-11e8-8958-6bb1a55bc40c.png)

I Also get a "404 Page Not Found" when entering /api.

Thank in Advance!

**Comment by deyvipunker** [comment]
Hello, Greetings from Peru, could you help me I have the same error, I am using windows server 2019, IIS
