### ISSUE TITLE
My Tickets

### ISSUE THREAD

**Issue by ghost** [opensupports/opensupports#428]
ERROR

My Tickets
Here you can view the tickets you are responsible for.
An error occurred while trying to retrieve tickets.

--------

New Tickets
Here you can view all the new tickets that are not assigned by anyone.
An error occurred while trying to retrieve tickets.

**Comment by nickbe** [comment]
This happens often after some idle time. I think there should not be any timeout for an app like this.

**Comment by alexrait** [comment]
It happens to me all the time now...
I have the latest version : 4.3.2
Are there any logs to see the exact reason for this?

**Comment by alexrait** [comment]
It happened to me after an upgrade and it was solved, once I fully refreshed the page with ctrl + F5.
