### ISSUE TITLE
Customize text in home page

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#431]
I need to customize that text to add information about used it from our customers but for that I have to manually edit the files of the tool.

**Comment by Mte90** [comment]
And it is not easy at all because to change that strings I have to edit a compressed javaascript file of 2mb.
Also from there is not possible to use HTML tags...

**Comment by xardtop** [comment]
Do you have any tutorial for that, or how to add a "main-home-page-portal__card" with "card_yellow" and customized text with icon
