### ISSUE TITLE
Blank screen on new installation ("Allow Override All" already done)

### ISSUE THREAD

**Issue by sysadt** [opensupports/opensupports#432]
I am trying to install Opensupports ticket system on Centos 7 using Apache.

Everything seems to be set up fine but when trying to access my page in the browser it shows a blank screen. 
As written in other issues, I have already inserted the `AllowOverride All` in my Apache config file but it still does not work...

Chrome console errors:

`/Opensupports/api/system/get-settings:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

`(index):1 Uncaught (in promise) Object
main.js:35 Uncaught (in promise) Error
    at v (main.js:35)
DevTools failed to parse SourceMap: http://myaddress/Opensupports/sass`

**Comment by ivandiazwm** [comment]
Could you check apache error logs? It seems there's an internal error in the PHP server side.

**Comment by thinkrapido** [comment]
/api/user and /api/system folder not present

![image](https://user-images.githubusercontent.com/1568087/50530042-5b37dc00-0afa-11e9-94f4-218a93e38b3f.png)

**Comment by thinkrapido** [comment]
logs normal

**Comment by nickbe** [comment]
Have you tried to install the dev or the release version?

**Comment by thinkrapido** [comment]
i downloaded release zip

**Comment by thinkrapido** [comment]
With release 4.3.2 and 4.3.1 the same

**Comment by nickbe** [comment]
This is probably some apache or PHP misconfiguration. I'd try to run the system on a local machine first to make sure it works for you and that you don't miss any configuration problem.

**Comment by thinkrapido** [comment]
got it:
change line in /etc/apache2/apache.conf in tag <Directory /var/www/html>
AllowOverride All

And don't forget to > sudo a2enmod rewrite

**Comment by nickbe** [comment]
Great. So it works now?

**Comment by cool-nicq** [comment]
> got it:
> change line in /etc/apache2/apache.conf in tag <Directory /var/www/html>
> AllowOverride All
> 
> And don't forget to > sudo a2enmod rewrite

@thinkrapido Thanks a lot.. solved mine too

**Comment by mredigonda** [comment]
Great, thanks you all guys for this, it will be useful for future references, for now, I'm closing this issue since it has been reported to be solved.

**Comment by oghenez** [comment]
Simply changing the php version in wamp64 version 3 to 5.6 solved the problem

**Comment by csfurlanetti** [comment]
Hello!
I am not able to make it work for users. In the http://localhost environment everything OK, but when I released it to users, it happens as in the attached video. Could you help me please? Thanks

https://user-images.githubusercontent.com/132863038/236718345-d462b894-c591-470b-b4d4-a1fede4802e1.mp4

**Comment by raraspri** [comment]
Hello, @csfurlanetti !!
I have the same problem.  Have you found the solution?  Thank you so much!!

**Comment by Amitaybi** [comment]
Hi,
this is an amazing project!
I'm facing the same problem as: https://github.com/opensupports/opensupports/issues/432#issuecomment-1537639925
when using localhost all works fine, when I use domain name or external IP address I get the error occurred message.
has anyone solve this issue?

![image](https://github.com/user-attachments/assets/ae126593-a2f9-4d69-8cfd-5e9fb0c227cc)

**Comment by fromansyah** [comment]
> Hi, this is an amazing project! I'm facing the same problem as: [#432 (comment)](https://github.com/opensupports/opensupports/issues/432#issuecomment-1537639925) when using localhost all works fine, when I use domain name or external IP address I get the error occurred message. has anyone solve this issue?
> 
> ![image](https://private-user-images.githubusercontent.com/43774496/349114677-ae126593-a2f9-4d69-8cfd-5e9fb0c227cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTczODAsIm5iZiI6MTczNDQ5NzA4MCwicGF0aCI6Ii80Mzc3NDQ5Ni8zNDkxMTQ2NzctYWUxMjY1OTMtYTJmOS00ZDY5LThjZmQtNWU5ZmIwYzIyN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA0NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YTk1YWRjMTNkYjk4MGJhMDczOWVjZjI0NzQ5MjkxMTVlYTAxNWFlYTRiZDM2OWM4MmY3NGJmOGZjOGYxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GvBTdp3qSFS9uCzJbR7737liNO73Zwb2EieoOe9Hiog)

Hi, i'm facing the same problem..  have you found the solution yet? thanks

**Comment by senyalefoka** [comment]
@oghenez , @thinkrapido , @ivandiazwm and @nickbe Please help me here  I did follow "matlou@matlou:~/opensupports$ sudo a2enmod rewrite
Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2
matlou@matlou:~/opensupports$   systemctl restart apache2"
after that I get this error "
 You've no permission to access to this page."

**Comment by tiforestsun** [comment]
> Hello! I am not able to make it work for users. In the http://localhost environment everything OK, but when I released it to users, it happens as in the attached video. Could you help me please? Thanks
> 
>  Problem.mp4

Conseguiu resolver?
Did you manage to solve this problem?
