### ISSUE TITLE
Initial loading time of lists can be long or even indefinetely

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#434]
Seems like a severe bug. When entering the site for the first time, the loading time of lists is very long. Sometimes there's no list at all until I press F5 and wait for about 1 minute again.

**Comment by tarasian666** [comment]
Same on admin - staff list

**Comment by xenorites** [comment]
I have encountered this as well; my help desk is rather new, so my only big list is my users. It only has 80 members, so that's mildly concerning.

**Comment by nickbe** [comment]
After analyzing a bit of the client server communication I can only deduct that this is due to the basic javascript / server interface. It seems to me that there's no difference between 80 records and 8000 which we already tested so far. Backanswering times and delaysare always the same - so I guess there might be a chance to improve this by optimizing the api and javascript front.

Also there are times when the response comes after 30 seconds and at other timer the response seems to almost without delay. Chrome seems to be faster than Firefox here - iOS (latest iPhoneX Version) feels generally a little faster to me even over 3G which seems to prove that this has nothing to do with the amount of records you have.

Strangely enough there are cases where my mobile would not show any records at all for minutes and then suddenly after the next refresh it feels like you're on a local machine.

@ivandiazwm Is there anything we can help you with here? Any tests we can do or scenarios we should play through?

**Comment by ivandiazwm** [comment]
@nickbe Yes, this is an issue indeed. A few weeks ago I was testing OpenSupports on heroku and realized there was an issue with too heavy responses to API calls (they were taken too long and returning too much data).
I did some improvements since then that paginate all ticket list request and returns minimal data needed. These changes will be visible in the next release.

**Comment by nickbe** [comment]
Ah this would be great indeed. This problem was more serious in everyday use than I expected at first.
Thanks!

**Comment by nickbe** [comment]
Could you provide us with a temporary release?

**Comment by ffuentes** [comment]
Hello,
same issues, fresh install with only 2 users. Creating a ticket take about 3 min starting from the first one.

**Comment by nickbe** [comment]
Loading time seems to be fine now. Thanks for fixing 😃
