### ISSUE TITLE
Email already exists creating user in admin panel

### ISSUE THREAD

**Issue by chicheze** [opensupports/opensupports#435]
Hi, I've configured OpenSupports with user system and User Sign up disabled, I can't create a user in admin panel because "Email already exists". With User Sign up enabled I can't create a user in admin panel too, the error is the same. Thanks.

**Comment by chicheze** [comment]
Sorry, I have User System enabled and User sign up disabled because I want only an administrator can create users. Thanks.

**Comment by goldleewtje** [comment]
i had the smae issue but after a reinstall it worked for me somehow. maybe a flaw in the installation of the software.

**Comment by mredigonda** [comment]
It seems this is discussed in #457. Any new questions should go there, I'm closing this one for now.
