### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by SunnyTeater** [opensupports/opensupports#437]
Hi,

i know Internet Explorer is dead and etc...
but will opensupports compatible with IE in the future?
All i get at the moment is a blank screen. 

Or did i just something wrong? 

Regards,
Felix

**Comment by nickbe** [comment]
IE is indeed dead. So better assume there will be no solution for the problem

**Comment by nickbe** [comment]
No but honestly I do not know any client or anyone within our company who uses it.
So I simply think it's a waste of time. Everyone around me was happy that the IE era has ended.

**Comment by SunnyTeater** [comment]
We are working with 2008 servers, 2019 servers comming soon...

But on all machines ie is preinstalled, so most of the users are using it.
Sure we have chrome and Firefox also there, but I don't know why everyone
is still using ie..  maybe we need to force Firefox and Chrome :p

Okay, so I can say for sure its not a bug from my server. And I should not
hope for a fix :D

Am Fr., 11. Jan. 2019, 01:10 hat Nick <notifications@github.com>
geschrieben:
