### ISSUE TITLE
Cannot install, Blank Page

### ISSUE THREAD

**Issue by CapuzDE** [opensupports/opensupports#444]
If I want to install OpenSupports, I get a blank page instead of the installation wizard.

Picture:
http://prntscr.com/mdc59c

Error:
http://prntscr.com/mdc5t5

**Comment by rafacamargo123** [comment]
You have to allow the Rewrite Rules on .htaccess that comes. Just add this in your VirtualHost on Apache, replacing the path with your installation:

```
<Directory /var/www/html/support/>                     AllowOverride FileInfo                         </Directory>
```

**Comment by CapuzDE** [comment]
Same problem. @rafacamargo123 

I have write it in the .htacces
http://prntscr.com/mdqr7e

**Comment by CapuzDE** [comment]
Solved.

**Comment by autoran58386** [comment]
@CapuzDE what dis you do to solve this http://prntscr.com/mdqy0d

**Comment by rafacamargo123** [comment]
@autoran58386 Probably misplaced, it was outside the `<VirtualHost>`. Put it somewhere between the `<VirtualHost>` and `</VirtualHost>`

**Comment by rafacamargo123** [comment]
Actually, reading Apache docs seems like the directive `Directory` can be set outside the `VirtualHost`. Your Apache should have error logs that describe the problem. Look for `/var/log/httpd/*error*` files and post the error that appears when you get the error on browser.

**Comment by autoran58386** [comment]
Will check it thanks @rafacamargo123

**Comment by jueyuansanqv** [comment]
> Solved.

Hi @CapuzDE , I got the same error as you show on above(http://prntscr.com/mdc5t5), I'v try to put the 

<Directory /var/www/html/opensupports/>
AllowOverride FileInfo
</Directory>


in my .htaccess, also 000-default.conf file, but still not working for me. Any advice? Thx

**Comment by Justinzobel** [comment]
This should be added to the installation instructions.

**Comment by Kalid-Carvalho** [comment]
> Solved.
How did you resolve this issue? I did like you and it didn't work.
