### ISSUE TITLE
TIME ZONE

### ISSUE THREAD

**Issue by davidsfi** [opensupports/opensupports#445]
By going to settings -> system preferences in the admin panel, you can edit the "Default Timezone (GMT)" setting, however, there is no easy to access guide on what format does this form field uses (if I have GMT-6, should I write -6, GMT-6, or what?).

**Comment by davidsfi** [comment]
api/lib  data.php

DE ESTA FORMA SE INICIA EL CODIGO 

date_default_timezone_set('America/Mexico_City');

class Date {
public static function getCurrentDate() {
return date('YmdHi');
}

**Comment by hohoqq** [comment]
I fixed this problem by setting right default time zone in my server - https://losst.ru/nastrojka-chasovogo-poyasa-v-linux
