### ISSUE TITLE
API Authentification

### ISSUE THREAD

**Issue by pfenie** [opensupports/opensupports#45]
Hi,
Could you give me an example on how to authenticate a staff member with the API ? I use Guzzle an everytime i get INVALID_CREDENTIALS.
Sorry for my english.
Thanks

**Comment by ivandiazwm** [comment]
Are you passing the `staff` field as `1` or `true`? You can take a look to https://www.opensupports.com/apidoc/#api-User-Login-4.1.0

**Comment by pfenie** [comment]
Many thanks for your anwser,
My code here :

```
public function ops()
    {
        $client     = new Client(array('base_uri' => 'http://<myip>/ops/api/'));
        $request    = $client->request('POST', 'user/login', array('staff' => 1, 'email' => 'contact@<mydomain>', 'password' => '<mypassword>'));
        $response   = (string) $request->getBody();
        var_dump($response);
    }
```


The response :	

> {"status":"fail","message":"INVALID_CREDENTIALS","data":null}object(GuzzleHttp\Psr7\Response)#46 (6) {
>   ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
>   string(2) "OK"
>   ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
>   int(200)
>   ["headers":"GuzzleHttp\Psr7\Response":private]=>
>   array(5) {
>     ["Date"]=>
>     array(1) {
>       [0]=>
>       string(29) "Mon, 03 Jul 2017 05:47:10 GMT"
>     }
>     ["Server"]=>
>     array(1) {
>       [0]=>
>       string(22) "Apache/2.4.18 (Ubuntu)"
>     }
>     ["Set-Cookie"]=>
>     array(1) {
>       [0]=>
>       string(44) "PHPSESSID=b2etk2v03jmk8i8ck7s6s7na44; path=/"
>     }
>     ["Content-Length"]=>
>     array(1) {
>       [0]=>
>       string(2) "61"
>     }
>     ["Content-Type"]=>
>     array(1) {
>       [0]=>
>       string(16) "application/json"
>     }
>   }

What is wrong ?

**Comment by ivandiazwm** [comment]
Please make sure the data is arriving correctly.

You can add line [here](https://github.com/opensupports/opensupports/blob/master/server/controllers/user/login.php#L51), it would be the file `/api/controllers/user/login.php`:

    throw new Exception(Controller::request('email'));

this line will make an response with the email as `message`, so you can check if the email was sent correctly. Remember that is has to be sent as a form.

**Comment by pfenie** [comment]
Sorry but I always get the same response by Guzzle. Status is Ok (200) but nothing more.
I'm a bit disappointed...
I tried to install Kallys solution but 'Composer require...' did not twork.
Thanks for all...

**Comment by pfenie** [comment]
I changed my request with 'form_params' and it works now.
A lot thanks for your help...

**Comment by ivandiazwm** [comment]
Awesome!
