### ISSUE TITLE
German Language Issue

### ISSUE THREAD

**Issue by lyrics1988123** [opensupports/opensupports#450]
hey guys.. 
in the frontend when you create a new ticket theres a field for the title of the ticket. 
the issue is, that in german ALOT of people think that they need to put in their title like Dr., Prof, or something and not the title of the ticket.. 
could you please change it in the german translation so it is "Betreff" isntead of "Titel"? 
The word "Betreff" is the title of a email, or letter and of course its used in tickets aswell.

thanks!

**Comment by goldleewtje** [comment]
you can look up in the main.js where it is defined. so you can alter the text there on your own if you still need it changed.

**Comment by lyrics1988123** [comment]
worked, thank you very much!

**Comment by 7JuanCruz7** [comment]
Hi... We finished this feature and it will be uploaded in the next release. 
Regards 
OpenSupports Team.

**Comment by nickbe** [comment]
And again.... thanks *bow*
