### ISSUE TITLE
Ticket number not correlative?

### ISSUE THREAD

**Issue by gusarg81** [opensupports/opensupports#456]
Hi,

Fresh installed Open Supports and in DB I've set ticket-first-number to 1 (since I don't see this option in admin panel).
In other hand, seems ticket number is random? Is there a way to be correlative starting from 1?

**Comment by goldleewtje** [comment]
you can read out the ticket id instead of the ticket number but you have to alter some code

**Comment by gusarg81** [comment]
Mmm, thats not good I think. Most of the tickets system you can configure this and is not good algo if is random (you can see how works even here in the issue number).

Example, I've just modified the first ticket number to #1 and, like I said, modified ticket-first-number to 1 thinking that would fix this, but when created a second ticket, it assigned a number #89098 (for example). Thats bad.

**Comment by gusarg81** [comment]
So, there is no way to change this? Is not practical a all to have random ticket numbers...

**Comment by nickbe** [comment]
The thing is that ticket numbers SHOULD by all means be random. The reason for this is simply that you don't want others to see exactly how many tickets you had - or should I say ... problems! The second reason would be that giving others a correlation between the importance problems in relation to the numbers of tickets created can give them some leverage that you don't want.
So I think random ticket numbers are just fine.

**Comment by gusarg81** [comment]
Who cares how many tickets one have? First time i "read" this "why".
Most popular tickets system at least has this as a setting (example again, osTickets).

For me, the choice for random or correlative should exist.

And I know the response will be "then fork the code" :D

**Comment by nickbe** [comment]
After 30 years in the business I don't claim that clients do - I know it.
And yep, forking is what you usually do. Fork the code and do it your way.

**Comment by gusarg81** [comment]
30 years, ah? My Gosh, I should not star this issue in the first place!...
