### ISSUE TITLE
Unable to change subject on email templates with two Text fields

### ISSUE THREAD

**Issue by eleektro** [opensupports/opensupports#460]
Can not save the email template when changing the subject text on USER_PASSWORD & USER_EMAIL template fields.

**Comment by xenorites** [comment]
I am actually unable to change this template from the GUI at all - no error or anything, just a warning changes will be lost when I attempt to navigate away.

**Comment by eleektro** [comment]
@xenorites yes, same behavior. Cannot change ANY field of the USER_PASSWORD nor USER_EMAIL templates.

**Comment by 7JuanCruz7** [comment]
Thanks for reporting the issue. I was able to reproduce it.
@ivandiazwm can you take a look to this issue?
