### ISSUE TITLE
Installation page is blank

### ISSUE THREAD

**Issue by sparthe123** [opensupports/opensupports#474]
Hi, 

I downloaded the latest zip file, unzipped and moved the folder to webserver folder, But when I hit the URL to open , it just loads blank page, 
Console logs showing 404 error
/system/installation-done
http://mydomain.com/api/system/get-settings

When i check the unzipped folder , there is folder named system inside api folder. 

can someone help to install

**Comment by goldleewtje** [comment]
change line in /etc/apache2/apache.conf in tag <Directory /var/www/html>
AllowOverride All

**Comment by sparthe123** [comment]
Thanks for that , also Rewriteengine module was not enabled, that was stoping in blank page, It worked fine after enabling Rewriteengine module.
