### ISSUE TITLE
Image Upload is not working 

### ISSUE THREAD

**Issue by sparthe123** [opensupports/opensupports#475]
I'm trying to upload image inside Article, and it saves successfully but when we open the article image is not displaying instead, it shows the image path on the server 

as http://mydomain.com/api/system/download?file=

**Comment by goldleewtje** [comment]
all the files are getting stored in api/files. you have to sift thru the code and replace the path directory to where the files are getting saved at

**Comment by sparthe123** [comment]
can you guide where to update the code to change image directory .

I tried creating "system" directory under api , but still failing to show image.

**Comment by goldleewtje** [comment]
in api\libs you have controller.php in that file you have to search for the image path and change it to /api/files that did the trick for me. best of luck

**Comment by mredigonda** [comment]
Thanks for reporting!

If the issue was not solved please reopen it, but I'm closing this for now since there wasn't a response for a while.
