### ISSUE TITLE
(Gmail) SMTP not working

### ISSUE THREAD

**Issue by Briansmit** [opensupports/opensupports#477]
I like opensupports a lot, but sadly cannot get mail to work. 

Wish there was a test mail button / function as well.

Is there someone here who managed to get it working ?

**Comment by goldleewtje** [comment]
be sure to check the firewall that was my issue. but after i setup the ports correctly it worked

**Comment by Briansmit** [comment]
Thank You ! im using a webhosting company , (and in my case its not a firewall issue), can you please tell me which ports worked for you ? 

Example working config please?

**Comment by Briansmit** [comment]
firewall issue here as well - my host seems to block the smtp service of gmail
