### ISSUE TITLE
SMTP Server has no option to use TLS/SSL or set port anymore

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#482]
It seems we cannot set encryption method or smtp port anymore??
Therefore I cannot make this work here.

**Comment by spackmat** [comment]
Also for IMAP-connection and also missing encryption settings. In my case SMTP works without setting encryption settings or ports, but IMAP does not (STARTTLS doesn't work I think, so using TLS on Port 993 would be the correct setting).

**Comment by nickbe** [comment]
It looks like there's a new documentation for this here:
https://github.com/opensupports/opensupports/wiki/Configure-Settings

I really wonder why there's no hint anywhere for new parameters needed.
