### ISSUE TITLE
Imap: Internal server error

### ISSUE THREAD

**Issue by NLLucifer** [opensupports/opensupports#486]
When saving IMAP settings (Yes, I'm sure the settings are correct) I get the following Error: 

![image](https://user-images.githubusercontent.com/37590500/54028663-14bfc700-41a6-11e9-8dda-bc7dec56ec7e.png)
(Its dutch, but basically it says: Cannot connect to the specified server: Internal server error)
Console screenshot:
![image](https://user-images.githubusercontent.com/37590500/54028706-3e78ee00-41a6-11e9-90e6-dd5fa1c96bee.png)

**Comment by nickbe** [comment]
Maybe this is because of the missing port field. I don't know if there's any default value at all - but at least it seems that I cannot connect to the server anymore myself.  I hope the missing port and encryption settings are re-added again soon.

**Comment by matthewbacon** [comment]
After installation I too don't have a 'system' directory within 'api'

![image](https://user-images.githubusercontent.com/11006446/54070743-c40aa580-425b-11e9-904d-d3e74b699833.png)

**Comment by NLLucifer** [comment]
I do have the system folder and do have the port number. 
@nickbe See the wiki imap installation page. You have to specify the port in the imap string.

**Comment by ivandiazwm** [comment]
@matthewbacon we use `.htaccess` to map all requests to `index.php`, no `system` folder is used.

@NLLucifer It looks like there's some internal issue with the server, make sure Apache logs are OK. Maybe there's some missing dependency.

**Comment by NLLucifer** [comment]
@ivandiazwm Checked it out indeed, got it to work eventually. Since i'm running multiple PHP versions on my server, i thought the imap_open dependency was installed on all of them. Apearently it wasn't :')

**Comment by mredigonda** [comment]
I will close this for now, since it seems it is resolved now and there hasn't been a reply for a while.
Thanks for reporting and feel free to re-open this if the problem remains!
