### ISSUE TITLE
Update failed - FATAL Error

### ISSUE THREAD

**Issue by lyrics1988123** [opensupports/opensupports#489]
hey, got an fatal error after updating from 4.3.2 to 4.4.0.

Everything looks like its working, except the custom fields, they not show up =(

```
Begin update v4.4.0... [1/1] Update email settings.. 
Fatal error: Uncaught RedBeanPHP\RedException: OODB Store requires a bean, got: NULL in /www/htdocs/w00ff6fd/support.veteran-gaming.at/api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php:119 Stack trace: #0 /www/htdocs/w00ff6fd/support.veteran-gaming.at/api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(404): RedBeanPHP\OODB->unboxIfNeeded(NULL) #1 /www/htdocs/w00ff6fd/support.veteran-gaming.at/api/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(544): RedBeanPHP\OODB->trash(NULL) #2 /www/htdocs/w00ff6fd/support.veteran-gaming.at/api/models/DataStore.php(136): RedBeanPHP\Facade::trash(NULL) #3 /www/htdocs/w00ff6fd/support.veteran-gaming.at/version_upgrades/4.4.0/4.4.0.php(36): DataStore->delete() #4 {main} thrown in /www/htdocs/w00ff6fd/support.veteran-gaming.at/api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php on line 119
```

**Comment by ivandiazwm** [comment]
Please make sure you have these rows in `setting` table of your database:
`server-email` `imap-host` `imap-user` `imap-user` `imap-pass`, create them with an empty value if they don't exist.
Also,  `no-reply-email` should not exist, remove it if it is there.

That should do have a similar result to the upgrading script. After it, go to `Settings->Email Settings` and configure them if necessary.

What is not being shown in custom fields?

**Comment by lyrics1988123** [comment]
thanks, gonna try these all.
custom fields are not shown in the ticket-create window.. 

i tried to add a custom field "steam ID"(gaming community) but this field doesnt come up. maybe after the fix, ill let you know. thanks for the fast reply!

**Comment by lyrics1988123** [comment]
checked the db:
all these exists. but you typed "imap-user" 2 times, i only have it one time in the db
no-reply-email does not exist.

do i need to use imap? were using smtp at the moment

**Comment by ivandiazwm** [comment]
sorry, I meant `imap-pass` instead of `imap-user` (fixed it).
No, you don't need to use IMAP.

**Comment by mredigonda** [comment]
Thanks for reporting this, since this issue wasn't updated in a while, I'm closing it for now, but feel free to re-open it if the problems persist.

**Comment by webivan74** [comment]
Hello, we have a problem for imap config. This is the message

`<br />
<b>Fatal error</b>:  Uncaught Error: Undefined class constant 'USER_SYSTEM' in /web/htdocs/crm.euroconsumatori.eu/home/api/controllers/system/email-polling.php:33
Stack trace:
#0 /web/htdocs/crm.euroconsumatori.eu/home/api/libs/Controller.php(20): EmailPollingController-&gt;handler()
#1 [internal function]: Controller-&gt;{closure}()
#2 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route-&gt;dispatch()
#4 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()
#5 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()
#6 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride-&gt;call()
#7 /web/htdocs/crm.euroconsumatori.eu/home/api/vendor/slim/slim/Slim/Slim.php(1300):  in
<b>/web/htdocs/crm.euroconsumatori.eu/home/api/controllers/system/email-polling.php</b> on line
<b>33</b>
<br />`
