### ISSUE TITLE
Internal Server Error when i try to add a select custom field

### ISSUE THREAD

**Issue by luizzz** [opensupports/opensupports#491]
Version 4.4.
When i try to add a select custom field with 3 string options gives me an error 500 like the following:

`PHP Fatal error:  Uncaught Error: Undefined class constant 'INVALID_CUSTOM_FIELD_TYPE' in /var/www/html/gpsplay/suporteonline/api/controllers/system/add-custom-field.php:48\nStack trace:\n#0 /var/www/html/gpsplay/suporteonline/api/libs/Controller.php(31): AddCustomFieldController->validations()\n#1 /var/www/html/gpsplay/suporteonline/api/libs/Controller.php(19): Controller->validate()\n#2 [internal function]: Controller->{closure}()\n#3 /var/www/html/gpsplay/suporteonline/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)\n#4 /var/www/html/gpsplay/suporteonline/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()\n#5 /var/www/html/gpsplay/suporteonline/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#6 /var/www/html/gpsplay/suporteonline/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 /var/www/html/gpsplay/suporteonline/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call() in /var/www/html/gpsplay/suporteonline/api/controllers/system/add-custom-field.php on line 48, referer: (...)`

**Comment by nickbe** [comment]
Same error here when trying to poll some imap mails. wtf?

**Comment by luizzz** [comment]
Fixed when i manually updated ERRORS.php and EXCEPTIONS.php on folder /api/data.
Don't know why but has not been updated after 4.4.0 upgrade.
