### ISSUE TITLE
help with error: Could not connect to database

### ISSUE THREAD

**Issue by andresmorago** [opensupports/opensupports#492]
Hi

Im trying to run the installation procedure on a ubuntu machine.
PHP Version 7.2.15-0
ubuntu0.18.04.1
apache2
mysql  Ver 14.14 Distrib 5.7.25

I can get past step 1 and 2 but when typing the mysql information i get the "Could not connect to database " error.
My data on this step is
localhost
port 3306
blank for database
root user
root password

i will appreciate your help

thanks

**Comment by nickbe** [comment]
You have to create and provide an empty database for installation. 
So instead of blank you should enter the name of an existing database together
with a user who has the right to access the database.

**Comment by andresmorago** [comment]
hi.
thanks for the feedback. i just did and now i get a different error: DATABASE_CONNECTION

**Comment by andresmorago** [comment]
i jiggled around and found the issue. a permission that what mising for my remote user
