### ISSUE TITLE
About http and https and Email when ticket is opened

### ISSUE THREAD

**Issue by martincalatravabol** [opensupports/opensupports#493]
Hi, I have version 4.4 the last version. if I access with https into admin appears to test email settings etc.. with http this does not appears. http and https are lite diferent into admin section. There are any option to access always like https and all works fine without to put https ?

Another thing is when a ticket is created an I have received 1 email ticket with http with https not.
Please help me. Need to when a ticket is sent to a department and email is sent to staff.

Please help me to have all working correctly.

**Comment by cool-nicq** [comment]
depends on which OS platform u r working with?

`https://www.namecheap.com/support/knowledgebase/article.aspx/9953/38/iis-redirect-http-to-https` for windows 

`https://stackoverflow.com/questions/16200501/http-to-https-apache-redirection` for linux

you can use `https://letsencrypt.org/` for free SSL certs.

**Comment by mredigonda** [comment]
I'm closing this since there hasn't been a response for a long time.
Feel free to re-open it if the problem persists!
