### ISSUE TITLE
email already exists error

### ISSUE THREAD

**Issue by gzhn8686** [opensupports/opensupports#497]
i have a fresh installation of opensupports but when i try to create a new user from both admin panel and homepage, it gives an error saying email already exists but i'm definitely sure the email address is not registered.

any solution? thanks. 

you can check on live website. php version is 5.6.4
[http://caredestek.com](url)

**Comment by cool-nicq** [comment]
is it the fresh installation?
did you edit the source code anywhere?
did you delete the users from ban list after deleting the user?

because i faced the same issue at beginning when i tried editing the MailSender.php

**Comment by mredigonda** [comment]
We already have a discussion about this in #457, so please comment there any issues you have.
