### ISSUE TITLE
NECESSARY FEATURE: more than 1 image up load.

### ISSUE THREAD

**Issue by adavie1** [opensupports/opensupports#517]
Currently, it seems you can only upload 1 image or file per ticket. This is a serious design limitation.

**Comment by lyrics1988123** [comment]
as a workaround we use containers such as zip or rar.. but most of the users dont even know how to do that properly and are creating an history-entry in the ticket for each screenshot..

very usable (not), when you have ~10 screenshots or more

**Comment by mredigonda** [comment]
Yes, this is necessary.

Let's migrate all discussion about this issue to #499.
