### ISSUE TITLE
Auto assignation

### ISSUE THREAD

**Issue by NLLucifer** [opensupports/opensupports#526]
Would it be possible to Automaticly assign a ticket to a operator based on the chosen subject?
If so, How is this possible now/can this be implemented in a new version?

**Comment by SunnyTeater** [comment]
Why it should be necessary?
If your customer create a ticket he can add a department. Everyone in this department gets an mail and see this ticket.
So your operator can easily pick the tickets he want...

**Comment by gprbf** [comment]
Why does not this work for me? All configured correctly, SMTP tested successfully, but the system does not associate the ticket with the team member, the ticket is left without owner. See issue # 556 for more details. can anybody help me?
