### ISSUE TITLE
API request /user/login using curl fails

### ISSUE THREAD

**Issue by j-c-h** [opensupports/opensupports#530]
I am unable to get /user/login API requests to work using curl. A 200 response is returned but always with INVALID_CREDENTIALS response. I've checked that the email and password are correct and consistent with what's in the database. What am I doing wrong?

$ curl -i -X POST -H "Content-Type: application/json" -d @login.json http://support.home/api/user/login
HTTP/1.1 200 OK
Server: nginx/1.15.8
Date: Fri, 26 Apr 2019 17:05:01 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: PHPSESSID=n6tkqt8kjh5kee470coeqalmqn; path=/

{"status":"fail","message":"INVALID_CREDENTIALS","data":null}

login.json has parameters for the /user/login API request in json format:

$ cat login.json
{
    "email": "user1@example.com",
    "password": "123456",
    "remember": "true",
    "staff": "false"
}

The user table in the database contains a password hash that verifies as valid for "123456".

mysql> select * from user where (id = 1);
|  1 | user1@example.com | $2a$10$p3fI1yCgWCJgOWDxsMSHKONe0W1EgdLqdVeYhmSaTLKGtDngL1XVK | Test User1 | 201904261119 |       2 |               NULL |     NULL |

**Comment by gonzo-coder** [comment]
In code:
```
 if(Controller::request('staff')) {
            return Staff::authenticate($email, $password);
        } else {
            return User::authenticate($email, $password);
        }
```
So if "staff": "false", i.e. it is a string with value "false".
PHP always casts non empty string (and non "0") to true.
So this code tries to authenticate this user as stuff.

This works just fine:
```
 {
"email": "user1@example.com",
"password": "123456",
"remember": "true",
"staff": "0"
}
```
or
```
{
"email": "user1@example.com",
"password": "123456",
"remember": "true",
"staff": ""
}
```
