### ISSUE TITLE
An error occurred while trying to retrieve tickets.

### ISSUE THREAD

**Issue by cool-nicq** [opensupports/opensupports#531]
Hi ,
I have installed OpenSupports v4.4.0 in Centos 7 x64. It was working perfect, but got an error today (An error occurred while trying to retrieve tickets) without making any changes.
the server cannot retrieve any data whether i click on "My Tickets" or "All Tickets".

I found the following logs while inspecting from Google Chrome:

**CONSOLE**
`DevTools failed to parse SourceMap: https://example.domain.com/sass
main.js:1 POST https://example.domain.com/api/staff/get-all-tickets 500 (Internal Server Error)
main.js:62 INVALID REQUEST to: /staff/get-all-tickets
main.js:62 undefined
main.js:35 Uncaught (in promise) Error
    at v (main.js:35)`

NETWORK:
`Request URL: https://example.domain.com/api/staff/get-all-tickets
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 192.168.10.5:443
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sun, 28 Apr 2019 10:13:23 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.17
X-Powered-By: PHP/7.2.17
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,mr;q=0.8,ca;q=0.7
Connection: keep-alive
Content-Length: 80
Content-Type: application/x-www-form-urlencoded
Cookie: PHPSESSID=p6oeml8jlj3946n8u6sv2ve25j
Host: example.domain.com
Origin: https://example.domain.com
Referer: https://example.domain.com/admin/panel/tickets/all-tickets
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
csrf_token: 0e7615062c4d616f5e4657398d7e49c0
csrf_userid: 1
page: 1
query: 
closed: 0`

**Comment by nickbe** [comment]
Did you solve the problem?

**Comment by cool-nicq** [comment]
nope.. thought the solution will take long enough as there are lots of unsolved issue. so better closed the ticket.

Anyway, thanks a lot for the concern.

**Comment by nickbe** [comment]
Please reopen the ticket. This seems like a severe bug worth investating.
@ivandiazwm Is it possible to find out what happens here. I wouldn't want this to happen in a productive environment.

**Comment by cool-nicq** [comment]
what logs should i post.. can you instruct so that i can have it here
