### ISSUE TITLE
No api/system folder generated

### ISSUE THREAD

**Issue by poldi1405** [opensupports/opensupports#533]
I'm currently trying to install Opensupports and having the same trouble no matter if I download the release from the website or building it on my own: There is no api/system folder.

While building these messages came in quick succession
```
cp: cannot stat 'server/composer.lock': No such file or directory
cp: cannot stat 'server/vendor': No such file or directory
```

As a result there is no way for me to install it.
[Generated opensupports_dev.zip](https://github.com/opensupports/opensupports/files/3137820/opensupports_dev.zip)

**Comment by isaacwalkercox** [comment]
I am having the same issue

**Comment by isaacwalkercox** [comment]
I think I have found the issue. The php script is using the wrong URL's! The system folder is under the controller folder. I would modify the php script to use /api/controller/system instead.

**Comment by isaacwalkercox** [comment]
Once I have set it up for myself, I will create a pull request

**Comment by ivandiazwm** [comment]
Duplicated from #568
