### ISSUE TITLE
How add a column on Ticket List menu?

### ISSUE THREAD

**Issue by GeneralDx** [opensupports/opensupports#537]
Hello DevTeam,,
I want add a column with the state of the ticket on the table ont the main menu when you are connected by the client side.

I find where you create the object but not where you say that there is 4 column with name as Number Title,Department and Date.

If someone could said me where they are said i will can add State

Thank you.

**Comment by GeneralDx** [comment]
Hello DevTeam,,
I want add a column with the state of the ticket on the table ont the main menu when you are connected by the client side.

I find where you create the object but not where you say that there is 4 column with name as Number Title,Department and Date.

If someone could said me where they are said i will can add State

Thank you.

**Comment by mredigonda** [comment]
Hi, we will work on adding a new column or some way to make it easy to tell the status of a ticket from ticket lists.

Since this is mentioned in other places (like #334, for example), we will be handling this issue in other places, thanks for reporting!
