### ISSUE TITLE
How to enable stats process?

### ISSUE THREAD

**Issue by vish45** [opensupports/opensupports#541]
Its a way to enable stats graphs? 
Thank you

**Comment by goldleewtje** [comment]
it shows the stats of the previous day for some reason it is active by default

**Comment by vish45** [comment]
... well mine doesnt work at all.
![image](https://user-images.githubusercontent.com/12300508/57331021-4a692980-70dd-11e9-9998-09f5659ced2c.png)

**Comment by chavesdev** [comment]
Same problem here

**Comment by lyrics1988123** [comment]
i think they deactivated it for some reason.. think i read this in some comment or so

**Comment by wixiwill** [comment]
same problem for me too ?? is there any way to resolve it ?
![image](https://user-images.githubusercontent.com/50709720/57867675-3ecae080-780a-11e9-9ca1-0b22b8b3aea0.png)

**Comment by vish45** [comment]
yeah thats what i know, and sorry i havent found the solution.
If i know something i let you guys know.
Greetings.

**Comment by ivandiazwm** [comment]
Stats are currently disabled due to performance issues. They can't be activated in the current version

**Comment by vish45** [comment]
Thank you!
