### ISSUE TITLE
Feature Request: Time Logging on a Ticket / Stopwatch in Ticket Response Field

### ISSUE THREAD

**Issue by sudopower** [opensupports/opensupports#543]
I'm still working on it, wanted to know if you think it's useful or have plans to include it ? 

![chrome-capture (1)](https://user-images.githubusercontent.com/14028003/57354228-9d4beb00-7188-11e9-82d2-259773565c62.gif)

**Comment by nickbe** [comment]
If we think it's useful ? :)
This will be an excellent feature. It looks simple enough to use...

**Comment by sudopower** [comment]
Cool.. will send a request once I'm done

**Comment by nickbe** [comment]
Thanks. Great contribution!

**Comment by computergott** [comment]
Hey there,

is the feature usable?

Thanks!
