### ISSUE TITLE
Api /system/get-stats don't work 

### ISSUE THREAD

**Issue by gdetra** [opensupports/opensupports#548]
I'm using v.4.3.2 and i have a problem with the api /system/get-stats. It gives me continuously this "error" even if the logged user is staff_3:
`{
    "status": "fail",
    "message": "NO_PERMISSION",
    "data": null
}`

For this request i send:
csrf_token   (token in the login response)
csrf_userid  (userId in the login response)
staffId          (staff id of logged user)
period          (a string like: 'WEEK', 'MONTH', 'QUARTER', 'YEAR')

There's something wrong?
Thank you.

**Comment by goldleewtje** [comment]
are you running it on a server or are you running it locally?

**Comment by gdetra** [comment]
I'm running it locally, but all the other api works

**Comment by goldleewtje** [comment]
then i dont know what caused it. i had a similar issue but that was cuz it didnt had suffecient rights on the server.

**Comment by gdetra** [comment]
but how it is possible if i'm staff_3? I have noticed that in v4.4.0 the code in the api system/get-stats is commented

**Comment by uneasymusic** [comment]
I can see it was disabled currently. 
I enabled it in my system and in api, but api is timing out getting data. 
Why is it generating  stat for statistics ? 
I also deleted all tickets, all logs and all ticketevents from tables, and it still generates stat table until php times out ( I have tried 2 minutes time out but it still times out and keeps generating rows in stat table)

**Comment by mredigonda** [comment]
Sorry for the incredibly late response, it seems that by this time the `/system/get-stats` path was disabled. I'll close this issue since it's kind of outdated now, feel free to open a new one if you run into problems!
