### ISSUE TITLE
An error occurred while trying to update settings: INIT_SETTINGS_DONE

### ISSUE THREAD

**Issue by oakkarmaung** [opensupports/opensupports#55]
It is showing when installing opensupports.

Please help.

**Comment by ivandiazwm** [comment]
This is probably because an error in the installation. Please, clean the database and retry to install.

**Comment by mredigonda** [comment]
This is really old, but to this day I still face the same problem. I get around it by:
1. Deleting the `/server/config.php` file
2. If running locally, use `127.0.0.1` instead of `localhost`
3. Making sure that everything is set up correctly with the database.
