### ISSUE TITLE
Error creating Custom field options

### ISSUE THREAD

**Issue by nispot** [opensupports/opensupports#558]
In spanish language an error happen when you try create a custom field with options.
**Solution:**
main.js file search:
"Seleccionar entrada",TEXT_INPUT:"Entrada de texto",OPTION:"Opción {índice}"
replace 
"Seleccionar entrada",TEXT_INPUT:"Entrada de texto",OPTION:"Opción {index}"
and works!

---------

En idioma español ocurre un error cuando se intenta crear un campo personalizado con opciones (select options, no así cuando se crea de tipo texto) para el registro de usuarios.

**Las solución** es reemplazar en el archivo main.js el texto
"Seleccionar entrada",TEXT_INPUT:"Entrada de texto",OPTION:"Opción {índice}"
por
"Seleccionar entrada",TEXT_INPUT:"Entrada de texto",OPTION:"Opción {index}"
y funciona!

Saludos. :)

**Comment by mredigonda** [comment]
Thanks for reporting, we will take a look at this, this probably happens with other languages too.

**Comment by mredigonda** [comment]
This problem was fixed, indeed, this problem happened not only in the Spanish version of translations, but in many others too, thanks for reporting!
