### ISSUE TITLE
Dashboard unavailable

### ISSUE THREAD

**Issue by cquintela** [opensupports/opensupports#561]
My dashboard show Currently Unavailable. Im using the system for 11 days already.

![image](https://user-images.githubusercontent.com/51704318/59268165-80d91d80-8c22-11e9-9885-6e4db3c487a9.png)

Running the opensupports @ Xampp over an Windows 10 install, using PHP 7.2.2.

Thanks.

**Comment by ivandiazwm** [comment]
This is intentional. This feature is currently disabled due to performance issues.

**Comment by bkerest** [comment]
Hello @ivandiazwm any idea if you are going to make it available again in future release?
Is there an roadmap for 2019?

**Comment by totz18** [comment]
hello @ivandiazwm any chance on activate the dashboard? since its hosted on the local site, I would like to active it and change information that it pull like ticket that are open for the longest time

thank you
