### ISSUE TITLE
Sending Website logo.png in messages rather the openSupports logo.png

### ISSUE THREAD

**Issue by stub2** [opensupports/opensupports#565]
I'd like to send my website logo.png rather than openSupports logo.png when sending emails to users. Which file(s) and edit(s) do I need to edit to achieve this. Thank you.

PS: This branding to our website shouldn't be this hard. I think it needs more attention. For the future. Branding messages we are sending to our users should always say they come from our website, not openSupports (in the from) and our logo in the body of the message.

**Comment by goldleewtje** [comment]
you can change the logo in the email settings in the ticket system. when you go to email template.

**Comment by stub2** [comment]
Yes it did. Easy :) I was expecting something very much more difficult. Thank you. Appreciated.

Now there is only the issue of the from showing openSupports instead of my domain? How to fix that?

**Comment by goldleewtje** [comment]
where do you mean? in the footer? or in de tabs?

**Comment by stub2** [comment]
No. In the email sent to the user, the From:  states openSupports when From should state my domain name (the uderlying email address is fine). Since the user is using my website for opening a ticket, they would be expecting to receive an email from my website. It doesn't make a whole lot of sense using From: "openSupports", when it should be From "my website".

**Comment by goldleewtje** [comment]
im pretty sure that needs to be changed in the code im not sure where to change it.

**Comment by kass507** [comment]
> No. In the email sent to the user, the From: states openSupports when From should state my domain name (the uderlying email address is fine). Since the user is using my website for opening a ticket, they would be expecting to receive an email from my website. It doesn't make a whole lot of sense using From: "openSupports", when it should be From "my website".

You must edit the file:
MailSender.php

It is located at: api/libs/
in line 19. You only have to change the text 'OpenSupports' for your website.

of
$ this-> mailOptions ['fromName'] = 'OpenSupports';
to
$ this-> mailOptions ['fromName'] = 'My Website';

**Comment by stub2** [comment]
That worked great. Thank you.
