### ISSUE TITLE
Export a Ticket into Github as an issue? 

### ISSUE THREAD

**Issue by dev0zz** [opensupports/opensupports#592]
Is it possible to export a Ticket as an github issue? It would be very nice to have this option, because then you could manage a whole github projects including some Tickets from customers.

**Comment by nickbe** [comment]
Honestly I feel that this kind of stuff doesn't make any sense at all.  if you're managing projects to GitHub then why using opensupports at all?

**Comment by mredigonda** [comment]
Sadly I don't see bindings with Github happening any time soon, I will close this issue for now in order to keep a cleaner history of issues.

Feel free to create another issue for any other suggestions you have, thank you!
