### ISSUE TITLE
password recovery admin

### ISSUE THREAD

**Issue by ghost** [opensupports/opensupports#595]
Password recovery for administrator is not working, I put the user email he says the email does not exist.

**Comment by mazierovictor** [comment]
I use php version 7.2 and mysql version 5.7.26-cll-lve

**Comment by mazierovictor** [comment]
The error initially described occurs when Use user system for clients is disabled.

**Comment by RamVal** [comment]
Having the same issue. The thing is, that we don't want the User System for clients. We only need users for ourselves and I don't want to change passwords through the database or such for my colleagues, when they forget theirs. That's not how it is intended I think.
PHP 7.2 and MySQL 5.7.27-0.
With User System for clients it works btw.

**Comment by mredigonda** [comment]
Hi, thanks for reporting this issue, I was able to reproduce it.

I'll be taking a look at this soon!
