### ISSUE TITLE
API don't work

### ISSUE THREAD

**Issue by gomulinsergey** [opensupports/opensupports#599]
Hey! API don't work. OpenSupports hosted on regular webhosting for sites. For example: try open http://host1775588.hostland.pro/api/system/email-polling, but i see only 404 error.

**Comment by omkar-vs** [comment]
you need to make a POST request: - http://host1775588.hostland.pro/api/system/email-polling?token=yourtoken

1. Download Postman
2. Create a New Post Request 
3. Enter your URL, a Key name and its Value (our token generated at OpenSupports)
4. Send!

**Comment by csaeum** [comment]
Postman answer

> {
    "status": "fail",
    "message": "INVALID_TOKEN",
    "data": null
}

the token is from the Admin an the Same from DB.
the Failure is the Same

**Comment by omkar-vs** [comment]
> Postman answer
> 
> > {
> > "status": "fail",
> > "message": "INVALID_TOKEN",
> > "data": null
> > }
> 
> the token is from the Admin an the Same from DB.
> the Failure is the Same

Did you turn off the User System? 
Also,ensure that you are posting as Body - Form Data (See Image)
![Check](https://user-images.githubusercontent.com/54441015/63644897-b44f2280-c710-11e9-9112-20dee796336a.png)

**Comment by csaeum** [comment]
what have you set in the individual tabs in Postman?

I can not get it or I get error 500 from the web server

**Comment by omkar-vs** [comment]
Show screenshot please
Individual tab in postman is empty. only body tab - form data field is used

**Comment by csaeum** [comment]
Ok, thank you, I thought Auth did something else.

**Comment by mredigonda** [comment]
Thanks a lot @omkar-vs and @bilalak for helping out!
I'm closing this issue but you can comment if there is any more doubt.
By the way, this is the [documentation for OpenSupports](http://www.opensupports.com/apidoc/), and you can check there what are the required parameters for every path of the API.
Have a nice day!
