### ISSUE TITLE
Problem with stats table of oppensupport

### ISSUE THREAD

**Issue by sherlock9712** [opensupports/opensupports#602]
hello, I have configured opensupport for my company, I have it in version 4.4.0, but I need the statistics table which appears to me as unavailable. How can i fix this?

![screenshot_20190808-114215_1680x1050](https://user-images.githubusercontent.com/53910995/62718537-f9b2e680-b9d3-11e9-9341-7d89bc0ed16b.png)

**Comment by idh-webdesign** [comment]
I have the same problem here.

**Comment by hellthere9** [comment]
me too

**Comment by mredigonda** [comment]
Statistics were turned off for performance issues. We apologize. They will certainly be available in a later version, but I have to say it is not our main priority right now.

And as always, if you have ideas on how to design this feature to overcome performance issues, we encourage you to contribute!
