### ISSUE TITLE
Want to customize language file and host on server

### ISSUE THREAD

**Issue by jueyuansanqv** [opensupports/opensupports#607]
As the title, I want change some of the chinese words and texts in file, and host on my server. Can this be the next feature coming to us?

**Comment by mredigonda** [comment]
Hi!
I don't think I get exactly what you are asking for, but if you feel some translation is wrong, you can send your pull request updating the language file [cn.js](https://github.com/opensupports/opensupports/blob/master/client/src/data/languages/cn.js).
Or maybe you are talking about modifying some texts particular to your company, in that case, most of the values that you want to modify should be editable in the settings.
