### ISSUE TITLE
Form is not cleared after creating an ticket

### ISSUE THREAD

**Issue by Grin0011** [opensupports/opensupports#608]
When a customer creates a ticket, the form is not cleared, so the customer can post it multiple times. That means that the ticket can be created multiple times. Is it possible to clear the form after submitting?

I am nog using the customer login.
Version 4.4.0

**Comment by omkar-vs** [comment]
Can you post your url of the ticketing page

**Comment by teflontoni** [comment]
I have this problem too.

https://support.buchliesegang.com

**Comment by Grin0011** [comment]
The ticketing page is support.gjsoftware.nl

**Comment by mredigonda** [comment]
Hi everyone, thanks for reporting, ideally the customer should be redirected to the home screen of OpenSupports, but this was failing in the code. I fixed it and this will be available for the next release.
