### ISSUE TITLE
Feature Request: Disable Users

### ISSUE THREAD

**Issue by versavius** [opensupports/opensupports#61]
Hi at present we can delete and ban a user which deletes all their current tickets.

Can we have the option to disable a user please?

In the event of a user leaving a company we would not want to delete all their tickets, but we would want to disable them from being able to login again.

Could this option be added please ?

Thanks

**Comment by ivandiazwm** [comment]
This is interesting, we haven't thought about this use case. We will add this feature in a future release. Thanks a lot!

**Comment by Sinetiqueta** [comment]
Nice!

**Comment by versavius** [comment]
Awesome thanks for listening!

**Comment by ivandiazwm** [comment]
This has been released in the v4.3
