### ISSUE TITLE
Ticked closed by others is still visible in All Tickets

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#612]
If I close a ticket disappear in that list but if others do the same they are still available.

**Comment by mredigonda** [comment]
Hi, thanks for reporting this.
Currently I can't reproduce the issue. Ideally, if anyone closes a ticket, everyone should be able to see it by going to all tickets, and then opting out "show closed tickets".

**Comment by Mte90** [comment]
I don't have anymore this problem because seems that the latest version fixed it (I closed the ticket and now is fixed).
