### ISSUE TITLE
Blank Installation Page

### ISSUE THREAD

**Issue by lucamonai** [opensupports/opensupports#616]
Hello There!

I have installed a Debian 9.1
I became a blank Page when i unziped the Installer, on Page Title i see "Open Support"

Installed Software:
Apache 2
PHP 5.6

**Comment by lucamonai** [comment]
Hello There!

I have installed a Debian 9.1
I became a blank Page when i unziped the Installer, on Page Title i see "Open Support"

Installed Software:
Apache 2
PHP 5.6

**Comment by PlataformasInformaticas** [comment]
You need set-up the virtual host of Apache
Here more information.

https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite-for-apache-on-ubuntu-14-04

This is old but useless.

**Comment by lucamonai** [comment]
Hii!

I already have an Virtual Host on Apache, i come to the php page but there is no information, i have tried PHP 5.6 and PHP7.2, both are not functionable :( 

this is the result page

`

  | <!doctype html>
-- | --
  | <html class="no-js" lang="">
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="description" content="">
  | <meta name="viewport" content="width=device-width">
  |  
  | <title>OpenSupports</title>
  |  
  | <link rel="stylesheet" href="http://desk.it-monai.at/support/css/main.css">
  | <link rel="icon" type="image/x-icon" href="http://desk.it-monai.at/support/images/icon.png">
  | </head>
  | <body>
  | <div id="app"></div>
  |  
  | <script>
  | opensupports_version = '4.4.0';
  | root = "http://desk.it-monai.at/support";
  | apiRoot = 'http://desk.it-monai.at/support/api';
  | globalIndexPath = "/support";
  | showLogs = false;
  | </script>
  | <script src="http://desk.it-monai.at/support/js/main.js"></script>
  | </body>
  | </html>
  |  

`

**Comment by lucamonai** [comment]
[desk.it-monai.at/support/](url)

**Comment by PlataformasInformaticas** [comment]
This is the configuration of /etc/apache2/sites-available/000-default.conf
`         DocumentRoot /var/www/html

        Options Includes
        <Directory "/var/www/html">
                RewriteEngine On
                AllowOverride All
        </Directory>`

use this for activate  rewrite on apache

`sudo a2enmod rewrite`

**Comment by lucamonai** [comment]
Hi! I have tried this, here is my VirtualHost Configuration, i also have enabled rewrite, but the Page is blank :(
`<VirtualHost *:80>
        ServerName desk.it-monai.at
        ServerAdmin luca.monai1@gmail.com
        DocumentRoot /var/www/desk.it-monai.at/html
    Options Includes
    <Directory "/var/www/html">
            RewriteEngine On
            AllowOverride All
    </Directory>
</VirtualHost>`

**Comment by lucamonai** [comment]
><VirtualHost *:80>
        ServerName desk.it-monai.at
        ServerAdmin luca.monai1@gmail.com
        DocumentRoot /var/www/desk.it-monai.at/html
    Options Includes
    <Directory "/var/www/html">
            RewriteEngine On
            AllowOverride All
    </Directory>
</VirtualHost>

**Comment by lucamonai** [comment]
Hi! I have tried this, here is my VirtualHost Configuration, i also have enabled rewrite, but the Page is blank :(

```
<VirtualHost *:80>
        ServerName desk.it-monai.at
        ServerAdmin luca.monai1@gmail.com
        DocumentRoot /var/www/desk.it-monai.at/html
    Options Includes
    <Directory "/var/www/html">
            RewriteEngine On
            AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by PlataformasInformaticas** [comment]
hi in the option Directory change this /var/www/html
```
<Directory "/var/www/desk.it-monai.at/html">
...
</Directory>
```

**Comment by lucamonai** [comment]
Hi!
Thank you, I forgot to change this!
Now i can reach the Page!
