### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by egs2003** [opensupports/opensupports#619]
![Unbenannt](https://user-images.githubusercontent.com/8488313/64778332-43a36500-d55c-11e9-9dae-56dd6a4119e3.png)

**Comment by mredigonda** [comment]
Hi Marcel,

Thanks for reporting, I already found the issue and fixed it, it will be correct for the next release.

**Comment by mredigonda** [comment]
This should be fixed in the project master branch already, and it will be available for the next release, thank you again for reporting this issue!
