### ISSUE TITLE
Default Department [Feature Request]

### ISSUE THREAD

**Issue by versavius** [opensupports/opensupports#62]
I know we can have multiple departments and switch between them which is great :)

But what if a user only uses one department 90% of the time, having to change the department constantly could be annoying.

What about if we can set the default department each user can use ? Just means less flicking through departments if you only want to see tickets from one dept.

Very useful if you have an IT, HR and Facilities dept, the facilities guys dont care about anything but their tickets (just like each other dept only caring about their tickets), so would be great to have  a default dept for each user

**Comment by ivandiazwm** [comment]
This sounds interesting and it could be in conflict #48. Maybe another idea cloud be to autoselect the last used department.

**Comment by mredigonda** [comment]
What if we allow admins to assign a default department, while having a "no default" option too?
I think this solves both issues.

**Comment by versavius** [comment]
Ok i took at #48 i think we need three options for a new ticket form:

1. Select Default (so a default department can be selected
2. No default so no department is selected so if the user tries to submit the form they get an error (just like if they did not enter any text for the title / content, this would force them to select a department.

This way the user can get both options.
