### ISSUE TITLE
[hpm error]

### ISSUE THREAD

**Issue by PlataformasInformaticas** [opensupports/opensupports#625]
When I tried run the server.
hpm error occurred while trying to proxy request

I try changing the port configuration from 8080 to another and nothing, localhost to ip and nothing.
Please help.

**Comment by PlataformasInformaticas** [comment]
I found at last 
`php -S localhost:8080`

**Comment by giacomobartoli** [comment]
@PlataformasInformaticas I am running into the same error but I still cannot start correctly opensupport. Could you kindly provide me more details about your fix?
