### ISSUE TITLE
Activity Graph currently unavailable

### ISSUE THREAD

**Issue by igpf** [opensupports/opensupports#644]
![image](https://user-images.githubusercontent.com/946962/67111458-efb31e00-f1a2-11e9-9e5d-4020544ef276.png)

I just did a fresh install about a week ago.  I haven't had this feature working yet, I thought it was a configuration issue.  But know I think that maybe I'm missing a library to be installed on the server.  

Please let me know, I love the product (btw) this was one of the feature I was really hoping to have available.

thanks again,
-ivan

**Comment by mredigonda** [comment]
Oh, Ivan, I'm sorry, we have disabled this feature temporarily for performance issues, but we didn't remove it from the system so we display it as disabled, it's not that you are missing any library.
Cheers, I hope to have this feature well implemented in the future.
For more information check out #646.
