### ISSUE TITLE
Stats are empty

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#646]
![immagine](https://user-images.githubusercontent.com/403283/67277783-e50cc780-f4c7-11e9-91a2-e5cd9bb075cd.png)
Looking from the browser inspector there is anything but I am not getting any errors in the console.
Maybe because I disabled the user signups?

**Comment by mbrignolo** [comment]
Same Issue

**Comment by Klauxz** [comment]
Hace the same issue, maybe need a minum tickets for work?

**Comment by mredigonda** [comment]
We had some performance issues with the statistics and we decided to turn them off, we will work on adding this feature back again in the future. Sorry for the inconvenience.

**Comment by Mte90** [comment]
So is better to remove the section or other people will open a ticket like this asking for missing stats and instead will get a closed ticket
