### ISSUE TITLE
Default language not set

### ISSUE THREAD

**Issue by ivandiazwm** [opensupports/opensupports#65]
If you go to `admin->system preferences` and you choose, for example, `Spanish` as the only supported and allowed language, the `Default Language` field will change its value to `Spanish` (which is correct); but after updating the settings, it doesn't get updated as the default language in the `setting` table of the database (unless you actually open the dropdown and select it).
If you then go the app home, the language selected by default will be Spanish but it will be all in English (even if you erase the LocalStorage and reload), because it is not changed in the database.

**Comment by guillegiu** [comment]
I guess this is a Front-end issue because i been testing it with the api , and  I didn't see any error in the database.
