### ISSUE TITLE
Installation wizard not working

### ISSUE THREAD

**Issue by Kallys** [opensupports/opensupports#7]
Hi !
OpenSupports sounds promising, I was about to test it in order to know if I could easily integrate it with one of my project (since there is absolutely no API doc yet), but I'm unable to launch the start wizard (unzing the given zip, and following installation instructions).

Got 3 HTTP404 while requesting host/os/ (host base route).

Maybe I miss some prerequisites ?
[Wiki](https://github.com/opensupports/opensupports/wiki/Installation) only mentions PHP + Mysql + PDO.

![screenshot](https://cloud.githubusercontent.com/assets/1195845/25673022/383fe044-3036-11e7-8a62-4e9ec5510109.png)

Thanks!

**Comment by ivandiazwm** [comment]
It looks like the server is ignoring the `.htaccess` of the `api` folder.
Are you using an Apache webserver? I will add it to the installation wiki.
Another possibility is that you have disabled the .httaccess override (it should be `AllowOverride All` in the apache configuration file).

Thanks for reporting it.

**Comment by Kallys** [comment]
Yep, I'm using Apache, and you're probably right, it may be a misconfiguration issue (but I did `AllowOverride All `)
What is strange is that logs seems to indicate the right .htaccess is used.
I will inspect that if I have time, unless you got a suggestion ?

Apache mod rewrite log:
```
[rewrite:trace3] mod_rewrite.c(475): [perdir /var/www/support/api/] add path info postfix: /var/www/support/api/system -> /var/www/support/api/system/get-settings
[rewrite:trace3] mod_rewrite.c(475): [perdir /var/www/support/api/] strip per-dir prefix: /var/www/support/api/system/get-settings -> system/get-settings
[rewrite:trace3] mod_rewrite.c(475): [perdir /var/www/support/api/] applying pattern '.*' to uri 'system/get-settings'
[rewrite:trace4] mod_rewrite.c(475): [perdir /var/www/support/api/] RewriteCond: input='/var/www/support/api/system' pattern='!-f' => matched
[rewrite:trace4] mod_rewrite.c(475): [perdir /var/www/support/api/] RewriteCond: input='/var/www/support/api/system' pattern='!-d' => matched
[rewrite:trace2] mod_rewrite.c(475): [perdir /var/www/support/api/] rewrite 'system/get-settings' -> 'index.php'
[rewrite:trace3] mod_rewrite.c(475): [perdir /var/www/support/api/] add per-dir prefix: index.php -> /var/www/support/api/index.php
[rewrite:trace2] mod_rewrite.c(475): [perdir /var/www/support/api/] forcing '/var/www/support/api/index.php' to get passed through to next API URI-to-filename handler
[rewrite:trace1] mod_rewrite.c(475): [perdir /var/www/support/api/] internal redirect with /var/www/support/api/index.php [INTERNAL REDIRECT]
```

Apache (2.4) conf file:
```
Alias /support /var/www/support

<Directory /var/www/support>
        Require all granted
        AllowOverride All
</Directory>
```

**Comment by Kallys** [comment]
Ok, got it!
It work when I add a `RewriteBase /support/` to /.htaccess and `RewriteBase /support/api/` to /api/.htaccess files.
