### ISSUE TITLE
Feature Request: tags or categories for tickets (sub departments)

### ISSUE THREAD

**Issue by hansemschnokeloch** [opensupports/opensupports#71]
Hello,

Would it be possible to add tags or categories to tickets ?

**Comment by Sinetiqueta** [comment]
You can start to create different departments to classify the different tickets.
In my situation I'm trying with **Technical, Commercial, Information**.

Who adds the new ticket will be able to choose the department.
regards

**Comment by hansemschnokeloch** [comment]
I need a second level of classification in conjunction with department classification

Example : technical / touchscreen, technical / power, commercial / invoice, commercial / voucher...

**Comment by Sinetiqueta** [comment]
I understand.
Now is the staff time answer.

i jsut installed today to test it ;)

regards!

**Comment by ivandiazwm** [comment]
It seems that you're asking for a sub-departments feature, where a department can have multiple sub-departments and so on. It's planned to be done for v4.3 since we have some other priorities for v4.2 (next release).

**Comment by nickbe** [comment]
Well actually this is probably the same thing I've asked for long ago.
Having completely free tags per ticket would greatly improve how ticket could be searched
AND how they can be handled by staff.
Think about tags like 'BUG', 'IMPROVEMENT', 'REJECTED', 'IMPORTANT', 'UNIDENTIFIED' and so on....

**Comment by mredigonda** [comment]
This is planned for v4.4.

**Comment by nickbe** [comment]
So please let it be v4.4 release day tomorrow 😄
