### ISSUE TITLE
Blank Page install

### ISSUE THREAD

**Issue by allancmello** [opensupports/opensupports#716]
![image](https://user-images.githubusercontent.com/1229105/73847962-fe7f1880-4805-11ea-8847-f81a42f0b5b4.png)

I try **AllowOverride All** and **AllowOverride Fileinfo** in apache2, but this not work!

**Its run in VPS, Ubuntu 14.06 and Apache2**

Any help?

**Comment by angelosne** [comment]
Same here. Tried on Centos 8 vps and Ubuntu desktop.
