### ISSUE TITLE
Doesn't show stats

### ISSUE THREAD

**Issue by scorpaust** [opensupports/opensupports#740]
Hello!

After i install open supports and get everything working, my dashboard keep not showing any stats option.

Why this may be happening? My instalation returned no errors and my ticketing service is working.

Also sometimes, when i click to deliver some ticket to other agent, the option turns automatically to none. Then, I must click again to deliver him the correspondent ticket.

Another thing, in each agent profile, the number of tickets assigned, opened and/or closed isn´t updated below the profile photo.

Thanks!

**Comment by metricfoxagency** [comment]
Same here....I dont see the tab 'Statistics' at all

**Comment by hohoqq** [comment]
The same issue

**Comment by mredigonda** [comment]
Stats were disabled because of performance issues, we are working on those!

**Comment by eduardoyael** [comment]
Hello!
Statistics are still disabled?

Thanks!
