### ISSUE TITLE
Sorting Tickets

### ISSUE THREAD

**Issue by JuergenUniVie** [opensupports/opensupports#744]
<img width="148" alt="Bildschirmfoto 2020-03-06 um 10 12 34" src="https://user-images.githubusercontent.com/61051829/76069351-09f36a00-5f93-11ea-9b2a-2b38461c002e.png">
Please add the option to sort the tickets in the overall overview (staff).

**Comment by guillegiu** [comment]
Hi Juergen we are working on that, in the next release we will adding many sort options to tickets.
