### ISSUE TITLE
Creating an ARTICLE - Text alignement

### ISSUE THREAD

**Issue by Sinetiqueta** [opensupports/opensupports#75]
When you are creating a new article, you are not able to choose the text alignment, and always appears as CENTER, when could be better to align to the left (in spanish, english,... ) and other languages maybe at right,,,
regards!

**Comment by ivandiazwm** [comment]
Yes you're right. We should allow text alignment to be determined by the author. We'll add this to our bug list.

Thanks for your suggestion!

**Comment by Sinetiqueta** [comment]
you are wellcome!

**Comment by Sinetiqueta** [comment]
Closed. ;)
