### ISSUE TITLE
Email reply to tickets gets stuck: Uncaught Error: Call to a member function isTicketSession() on null 

### ISSUE THREAD

**Issue by beyto1974** [opensupports/opensupports#759]
Uncaught Error: Call to a member function isTicketSession() on null on api/controllers/ticket/comment.php:83

$this->session = Session::getInstance(); is not called I suppose.

Adding:
$this->session = Session::getInstance();
After:
public function handler() {

Works.

**Comment by guillegiu** [comment]
Hi beyto,  this is quite estrange,in the latests version you should able to see "this->session = Session::getInstance();" in line 43 of comment.php, it is called in validations.If you delete this line you will find that error "Uncaught Error: Call to a member function isTicketSession() on null on api/controllers/ticket/comment.php:83 "when you try to make a request. Can you give us more details about this?  wich version of OpenSupports are you using?

**Comment by beyto1974** [comment]
Version 4.6.1. I no more use it, sorry.

**Comment by guillegiu** [comment]
No problem, good luck.

**Comment by ezzra** [comment]
I have the same problem with 4.6.1 and the aforementioned solution works, just put

```
$this->session = Session::getInstance();
```

to line 81 of `controlers/ticket/comment.php`
