### ISSUE TITLE
question about Assing Tickets

### ISSUE THREAD

**Issue by Sinetiqueta** [opensupports/opensupports#76]
When a Customer adds a new ticket and he select the proper department.
Has an administrator to assing the ticket to the correct department or it can be done automatically?

I don't know if my question is clear... waiting your comments!

regards!

**Comment by ivandiazwm** [comment]
Every time a customer wants to send a new ticket, he has to select the department to which his ticket belongs. The ticket will be sent to that department. If a staff member thinks it is not the proper department, it can be changed.
