### ISSUE TITLE
email preview reply IMAGE_PATH_0

### ISSUE THREAD

**Issue by lexpre** [opensupports/opensupports#762]
Hi,
when an image is inserted in the text box of the ticket, the email sent does not display it ... the text "IMAGE_PATH_0" is displayed instead of the image.
Thanks for any reply.

**Comment by guillegiu** [comment]
HI lexpre, thanks for reporting this this is a bug.We will fix it in the next version

**Comment by guillegiu** [comment]
fixed on #765
