### ISSUE TITLE
Installation Issues - tuzinar3

### ISSUE THREAD

**Issue by Sinetiqueta** [opensupports/opensupports#78]
@tuzinar3, can you explain how is your installation?
In my short experience, can be able to install in a external server under Softaculous or locally using a portable Server (under Windows), with **Uniform Server Zero XII**

**Comment by tuzinar3** [comment]
in this topic https://github.com/opensupports/opensupports/issues/68

**Comment by Sinetiqueta** [comment]
I see

**Comment by Sinetiqueta** [comment]
Closed!
