### ISSUE TITLE
Can't attach certain files

### ISSUE THREAD

**Issue by andreantonacci** [opensupports/opensupports#781]
Hi all,

When trying to attach a file (both to a new ticket or in a comment) I get the following generic error: "An error occurred while trying to add the comment" (and nothing is logged in the console). 
![image](https://user-images.githubusercontent.com/50109671/81584488-17720980-93b3-11ea-8042-ca6927efba46.png)
Notice that I am able to add plain text comments, and also to attach most of the files (e.g., PNGs).  This mainly happens when attaching PDF files, but it doesn't occur randomly. In other words, _some_ files won't get uploaded, while other PDFs will do just as fine.

- All files are well below the maximum size limit
- The error seems to occur regardless of the user role (regular user v. staff)
- Files that won't get uploaded have no special characteristics compared to those that do get uploaded (I can open them on my PC, they don't seem corrupted, etc.)
- I tried to zip these files, but I get the same error 
- I have replicated the issue both on Chrome and Safari
- I have v4.6.1 installed and my machine satisfies all installation requirements

I found _similar_ tickets (#346 and #393). Following your suggestions, I checked in the settings table of the database. `ticket-gap` is prime, while I can't `file-gap` at all.

Any ideas?

**Comment by andreantonacci** [comment]
Fixed by updating POST max size and enable POST data reading.

**Comment by fdinardo** [comment]
@andreantonacci please can you elaborate your fix, how do you enable POST data reading and how do you update POST max size.
I tried to update `$maxSize` into the `FileUploader.php`, but no luck.

Thanks.
