### ISSUE TITLE
Email-Polling handler stops directly after call

### ISSUE THREAD

**Issue by joestr** [opensupports/opensupports#825]
Is this intended?

https://github.com/opensupports/opensupports/blob/92a96c276be014acce6cf4d9806414a601913ee9/server/controllers/system/email-polling.php#L23

**Comment by joestr** [comment]
https://github.com/opensupports/opensupports/commit/92a96c276be014acce6cf4d9806414a601913ee9#diff-dfd92344d19e008fd5a6b097fdac0a3aR23

**Comment by guillegiu** [comment]
Hi joestr  this is a mistake we took in  V4.7.0. You should able to use the path well deleting that line.
We have fixed that in the Latest Release.
#839
