### ISSUE TITLE
Force Throwing Exception on email-polling controller

### ISSUE THREAD

**Issue by dragongun200** [opensupports/opensupports#834]
Force Throwing Exception on email-polling controller...

`curl --data "token=PFwkPbkYdl0BDXXXXXXX" https://XXXX.de/api/system/email-polling`
Result: 
`{"status":"fail","message":"NO_PERMISSION","data":null}`

FILE: root/api/controllers/system/email-polling.php:23
`throw new RequestException(ERRORS::NO_PERMISSION);`

**Comment by marekrz** [comment]
i have same problem :-(

**Comment by dragongun200** [comment]
@marekrz just remove the line ^^

**Comment by guillegiu** [comment]
This is an error we got on release 4.7, as dragongun said, the path works well without that line.
We have deleted it in the new Release
#839
