### ISSUE TITLE
Upgrade v4.6.1 -> v4.7.0

### ISSUE THREAD

**Issue by philippeladame** [opensupports/opensupports#836]
Hello
I tried to follow the https://github.com/opensupports/opensupports/wiki/How-to-Upgrade instructions but after downloading and extracting the files, I can't find the "version_upgrades/4.7.0/" mentioned in step 4.

Did I miss something ?

Regards
Philippe

**Comment by guillegiu** [comment]
HI philip, this is in weird, 
I have downloaded the .zip right now and I found the folder.
Try with the .zip included in the Assets of the Release  4.7.0
https://github.com/opensupports/opensupports/releases

**Comment by philippeladame** [comment]
Thank you.
Probably I had downloaded the wrong first install version.
It's okay now.
