### ISSUE TITLE
Inaccessible admin panel

### ISSUE THREAD

**Issue by xoscov** [opensupports/opensupports#843]
I cannot access the administration panel, I have my own server with Fedora Server 31 when entering
_**http: //mydomain/support/admin**_  gives me an apache error

Not Found
The requested URL was not found on this server.

**Comment by waml0478** [comment]
Can you see http://mydomain/support ?

If you can't see it, there's was a problem with install or update...

**Comment by xoscov** [comment]
@waml0478 Yes, if I can see it, I already inadvertently solved it anyway. Yesterday I found an article that explained that you have to copy the file s**_upport/api/.htaccess_** to **_support/.htaccess_**, I did it and with that it was solved, I can see the control panel.

**Comment by xoscov** [comment]
[La página de administración no se está cargando # 476](https://github.com/opensupports/opensupports/issues/476) ese es el articulo donde me dieron la pista y con lo que lo solucione por si a alguien le vuelve a pasar lo mismo muchas gracias de cualquier forma @waml0478
