### ISSUE TITLE
Possibility to change the logo? 

### ISSUE THREAD

**Issue by titus-be** [opensupports/opensupports#854]
Is there a way to change the logo on the admin page?

**Comment by titus-be** [comment]
And the mail templates?

**Comment by Forz70043** [comment]
Hi,
if you mean the icon of staff members, it's possible. 
Go to my account, and upload the image.

Icon of email template: go to settings =>email settings => and change the URL of logo

**Comment by Forz70043** [comment]
@titus-be close issue if u solved it
