### ISSUE TITLE
No Support for PHP7?

### ISSUE THREAD

**Issue by c0fe** [opensupports/opensupports#86]
Does OpenSupports really does not support PHP7?

I have been trying to install it while using PHP version 7 and I am getting a blank page, was this issue really no corrected?

**Comment by mredigonda** [comment]
Well, OpenSupports is expected to support PHP7 but there seems to be a problem with it (as you can see [here](https://github.com/opensupports/opensupports/issues/81) and [here](https://github.com/opensupports/opensupports/issues/54).

Thanks for reporting, we now know that this is a major issue. We will look into this problem soon.

**Comment by c0fe** [comment]
One thing I would like to add, this is being run on Inmotion Hosting shared hosting

**Comment by gerickt** [comment]
same problem here ...

**Comment by tuzinar3** [comment]
Me too, see what I thought

https://github.com/opensupports/opensupports/issues/68

**Comment by ivandiazwm** [comment]
I tested it in PHP 7.1.10 and I found a problem with the code. Please, tell me if by removing [this line](https://github.com/opensupports/opensupports/blob/master/server/models/DataStore.php#L137) it works.

**Comment by c0fe** [comment]
@ivandiazwm no, that does not help resolve my issue, just generates a 500 error.

**Comment by gerickt** [comment]
@ivandiazwm the problem persists
500 error

**Comment by ivandiazwm** [comment]
@c0fe @gerickt Could you post the `error_log` from apache?

**Comment by cherrykoda** [comment]
Also having an issue with unset($this) from within the DataStore.php file (line 137). 

Swapping the server to PHP 5.6 fixed the issue. Will this project be upgraded to work with PHP 7.0 in the near feature.

**Comment by Kallys** [comment]
Actually, I'm running opensupports on a production server with PHP 7.0.
Issue with `unset($this)` [is related to](https://wiki.php.net/rfc/this_var) PHP 7.1.

**Comment by ivandiazwm** [comment]
`unset($this)` issue has been fixed and deployed

**Comment by XxAlpacinoxX** [comment]
@ivandiazwm 
hello i only get a blank page. I have now tried php 5.6, php 7.1, nothing changes.

**Comment by XxAlpacinoxX** [comment]
<img width="1788" alt="Bildschirmfoto 2020-01-28 um 17 13 00" src="https://user-images.githubusercontent.com/59840336/73282217-7f7c5580-41f1-11ea-97c9-61f9282c48f4.png">
Can you help me please?
