### ISSUE TITLE
Get List of closed tickets via the API

### ISSUE THREAD

**Issue by christheradioguy** [opensupports/opensupports#873]
Wondering if it's possible to get a list of all tickets (open and closed) via the API?  Right now running /staff/get-tickets or /staff/get-all-tickets only seems to return tickets that have closed=false.  I need to be able to retrieve closed and open tickets.

**Comment by mredigonda** [comment]
Both paths `/staff/get-tickets` and `/staff/get-all-tickets` receive an optional parameter `closed`, if it is set to true, it will also return tickets that are closed.
This isn't being shown currently in the documentation, I'm checking out why, thanks for pointing this out!

**Comment by christheradioguy** [comment]
Thanks!  That does exactly what I need it to.
