### ISSUE TITLE
The account info of demo is invalid.

### ISSUE THREAD

**Issue by liangxinhui** [opensupports/opensupports#9]
The account info from here:
https://www.opensupports.com/demo/

Demo with User System
Login/Admin email: demo@www.opensupports.com
Login/Admin password: demouser

Demo without User System
Admin email: demo@www.opensupports.com
Admin password: demouser

------

both of the demo sites have the same problem.

eg:
https://www.opensupports.com/demos/demo2/admin

![image](https://cloud.githubusercontent.com/assets/2174869/25732522/1ae14aa8-3183-11e7-9e61-729b7608435d.png)

**Comment by ivandiazwm** [comment]
The email shouldn't have `www.`. 
I've updated the demo info. Thanks for reporting it and sorry for the inconvenience.
