### ISSUE TITLE
Tickets ID duplication

### ISSUE THREAD

**Issue by tylp** [opensupports/opensupports#90]
Hello,

Some tickets ID are duplicated (cf screenshot).
Selecting a ticket that shares an id with another will show the most recently aded.

<img width="962" alt="sans titre" src="https://user-images.githubusercontent.com/16817995/32232220-dd348a32-be57-11e7-97e4-73255931ece3.png">

**Comment by ivandiazwm** [comment]
It looks that there is an issue with the `isPrime` function we use for the linear congruential generator.
I have test it by brute-forcing random values and it collides. I have make an update [here](https://github.com/opensupports/opensupports/pull/91/commits/aa533856d5622d38e6fb56ac0ab205038d03752b#diff-87bfc0d53b70fb5415d76cd04cc0312d) that works. We will to add some strong tests for the library and also a migration script for the next version.

Thank you for reporting this issue.

**Comment by ivandiazwm** [comment]
Fixed
