### ISSUE TITLE
missing checkboxes

### ISSUE THREAD

**Issue by GrafVoicu** [opensupports/opensupports#914]
Hi,

i just fresh installed opensupports und testing it. while doing so i found out that i got no checkboxes. cant check the departments for the new invitation. same at other options, too

i'm running opensupports on a synology diskstation with apache 2.4 and php 7.4 and mariadb 10 sql

what can i do?

thanks

![2020-10-07 10_43_39-Window](https://user-images.githubusercontent.com/72493916/95308298-04903200-088a-11eb-8127-06274f74bc74.jpg)
![2020-10-07 10_54_57-Window](https://user-images.githubusercontent.com/72493916/95309562-977d9c00-088b-11eb-809c-a50c03ace248.jpg)

**Comment by mredigonda** [comment]
Hi, thanks for reporting this issue!

What web browser (Chrome, Safari, Firefox, etc.) are you using? Also what version of it?

Also please open the developer tools (press F12 while on the page), then select the "Console" tab, and please show us the output after you see these pages without checkboxes.

Thanks!

**Comment by GrafVoicu** [comment]
i have found the problem, we are running an pi-hole-adblock-server and this was the criminal. whitelisting the opensupport-server and now it works fine.
