### ISSUE TITLE
Problem Upgrade 4.6 or later

### ISSUE THREAD

**Issue by sebsofunky** [opensupports/opensupports#915]
Hi Dev Team,
I can't and i don't understand how to update opensupport.
When I upload the whole downloaded directory, I run 4.6.0.php I get an error message.
When I upload only the versions_upgrade folder and executed the 4.6.0.php file I have the success message but I am still in 4.5.0.
Do you have a specific tutorial for the update?

Kind regards
Seb

**Comment by mredigonda** [comment]
Hi @sebsofunky, thanks for reporting your issue.

We do have a guide on how to update: https://github.com/opensupports/opensupports/wiki/How-to-Upgrade

But if you run into an error message while executing those steps please save it so you can share it here with us later.

Also please don't forget to always backup your data before doing upgrades (and save them for some time even after the upgrade is successful).

I hope that helps you out!

**Comment by sebsofunky** [comment]
Yes I read it but must I do upload on my server the whole directory ? (folder api + images + version_upgrades + bundle.js and index.php) ? 
And after execute the 4.6.0.php file ?

**Comment by mredigonda** [comment]
Yes, you must replace all those folders and files in your server (back them up first).

In the case of upgrading from 4.6.0 to 4.6.1 there is no `4.6.0.php` file, but for most others, yes, you would have to run the corresponding update script.

Please let me know if you continue having problems!

**Comment by sebsofunky** [comment]
I done 
Begin update v4.6.0... [1/4] Creating Tables... [2/4] Updating ticket table... edited_title column already exists [3/4] Updating APIkey table... type column already exists [4/4] Updating Log table... author_name column already exists Update Completed!

But when I connect, I am on 4.5.0
![Capture d’écran 2020-10-08 à 16 37 15](https://user-images.githubusercontent.com/29373263/95473818-c3307d00-0984-11eb-99b1-21544432c659.png)

**Comment by mredigonda** [comment]
Hmmm, I believe that text should be updated when you replace the `bundle.js`, @guillegiu is this the case?

Try clearing the cache with `CTRL+SHIFT+F5` (in chrome-based browsers) and see if it still appears.

**Comment by sebsofunky** [comment]
I replace the bundle.js file manually. I clear the cache, connect with an another web browser but nothing. So I don't know if the update is OK

**Comment by guillegiu** [comment]
Hi @sebsofunky,
Are you able to use the features of the V4.6.0? like _Invite users, support ticket custom list, edit ticket title_ ?

**Comment by sebsofunky** [comment]
Yep,
After several attempts, it works ! I updated the 4.8.0 !
Thanks for your support !
Seb
