### ISSUE TITLE
In the Admin panel, add member button

### ISSUE THREAD

**Issue by Ghost94** [opensupports/opensupports#93]
Hi,

Can the add member button be added to the users section in Admin panel?
At this point, admin can give support for a certain group.

Thank you..

**Comment by ivandiazwm** [comment]
Hi currently, the only way to register a user by the admin panel is by using the `CSV Import` feature.
However, adding an "add user" button has been suggested many times, so I will add this to our kanban.

**Comment by Ghost94** [comment]
Hi,

A button is really a more practical method. I congratulate you for your work.

Thank you for your interest and your reply.

**Comment by ivandiazwm** [comment]
This has been released in the v4.3
