### ISSUE TITLE
Email with non ASCII characters

### ISSUE THREAD

**Issue by Kallys** [opensupports/opensupports#95]
Both email subject and body are not sent properly with non ASCII characters.
Not sure if it is a server configuration or code bug.
For example, default subject for TICKET_RESPONDED in french is "#706441 Nouvelle rÃ©ponse - OpenSupports" instead of "#706441 Nouvelle réponse - OpenSupports".
It is the same for email body although it is possible to work around using [html entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Character_entity_references_in_HTML).

**Comment by ivandiazwm** [comment]
I see. Thanks for reporting this issue.

**Comment by ivandiazwm** [comment]
@guillegiu Maybe just adding this line
```
$this->mailerInstance->CharSet = 'UTF-8';
```
to  https://github.com/opensupports/opensupports/blob/master/server/libs/MailSender.php#L73
