### ISSUE TITLE
Department not listing on user view (Only listing  'Help and Support')

### ISSUE THREAD

**Issue by maxinjohn** [opensupports/opensupports#96]
Hi,

While I login and create a ticket as user there only a single department is seeing which is Help and support.

No others are showing there. Is there any fixes for  this. Please reply me ASAP  and this is urgent.

Regards,
Maxin

**Comment by ivandiazwm** [comment]
You can edit the departments on the admin panel `/admin` by clicking on Staff->Departments

![departments](https://user-images.githubusercontent.com/6447076/32927864-ce8439dc-cb2d-11e7-8900-a69839128aaa.png)

**Comment by maxinjohn** [comment]
Hi, 
Thanks, but there are already 3 departments are present including Help and support but only the default one is listing in user view but in staff view they are listing correctly...

**Comment by ivandiazwm** [comment]
That can be caused because of the local storage. Try by logging out, refresh the page and then log in aging.

**Comment by maxinjohn** [comment]
User View
------------
![image](https://user-images.githubusercontent.com/33740873/32928229-f6f6e1fa-cb76-11e7-9475-df2e59e87109.png)


Admin View
--------------
![image](https://user-images.githubusercontent.com/33740873/32928268-221885dc-cb77-11e7-80c3-3896229a6ed6.png)

This is the issue that I'm facing. Please suggest the fix. If you want I can give you the logins.

Regards,
Maxin

**Comment by ivandiazwm** [comment]
It's weird. Can you log in with the user in incognito mode to see if the issue still there?

**Comment by maxinjohn** [comment]
Hi

Strange, It works now.

Thank you.

:)
