### ISSUE TITLE
How do I install this ?

### ISSUE THREAD

**Issue by nwlguy** [opensupports/opensupports#988]
I really don't know how and where to install this...
Can someone guide or help me ? 
What server do I need ?
What commands ?

**Comment by nwlguy** [comment]
Seems like linux but where is the ui, is it windows ?

**Comment by Techciti877** [comment]
This is a web based program.  You will need to have a Linux server.

**Comment by nwlguy** [comment]
which version do you recommend ?

**Comment by Techciti877** [comment]
Unfortunately I have only installed the latest version 4.9.0.  This is the version I installed and have been using for a week.

**Comment by nwlguy** [comment]
got it.
