### ISSUE TITLE
Forgot Staff password.

### ISSUE THREAD

**Issue by maxinjohn** [opensupports/opensupports#99]
Hi,

I have forgot my admin login, how can I reset from back end? or from phpmyadmin.

Which hashing is used for password encryption.

Urgent.

**Comment by maxinjohn** [comment]
I have fixed it

**Comment by bromoapp** [comment]
@maxinjohn  Hi... which hashing to use? I also bumped into this matter please help

**Comment by mredigonda** [comment]
Take a look at #161, we are using bcrypt.
