### ISSUE TITLE
link in Ticket Responded email does not work - wrong path in url

### ISSUE THREAD

**Issue by crg-adale** [opensupports/opensupports#994]
Installed version is 4.8.0 (unable to upgrade to 4.9.0 - different issue, but may be part of the issue)

The url link in Ticket Responded (check ticket button) to is such:
.../support/check-ticket/135150/email@address.com

The /support folder was where I had originally installed OpenSupports.
In my attempts to upgrade to 4.9.0 I ended up deleting this folder, and reinstalling 4.8.0 in new folder /helpdesk

If I manually change the link in the browser (from /support to /helpdesk ) it works.

Where do I need to look to change where this folder path is getting loaded from incorrectly?

**Comment by mamossa** [comment]
Can you show me how

**Comment by crg-adale** [comment]
> Can you show me how

I am not sure I know what you are asking?  Show you image examples, or how I manually typed in the correct folder name in the browser address bar?

**Comment by kiyoujim** [comment]
Boa tarde,

como está o apontamento do seu DNS?

**Comment by Techciti877** [comment]
I believe what your are looking for is in the database in the Settings table under URL.

**Comment by crg-adale** [comment]
Yes it was. That was so simple.  
In Settings, I updated the "Support Center URL" and now the responded to emails contain the correct link address.
Thanks.
