### ISSUE TITLE
issue smtp exchange

### ISSUE THREAD

**Issue by EnricoSx** [opensupports/opensupports#995]
Hello
i try to configure smtp server

https://i.ibb.co/q0Fc8kD/2021-03-26-17-13-57-Ticket.jpg

also i try exchange 2016

**Comment by kiyoujim** [comment]
Boa tarde Enrico, 

eu consegui fazer o meu funcionar na v4.9.0.

Servidor SMTP: ssl://smtp.DOMINIO.net.br:465

**Comment by EnricoSx** [comment]
My shared hosting have a firewall. 😑
