### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by alexkidrd** [opensupports/opensupports#999]
i'm using open supports  to manage my tickets.
The application is working good, but the time showed for my ticket is different for my country, I'm in Brasil -4 GTM, in my tikets is 0 GTM or somthing. I try to change, nothing is happen. Can you show me steps to fix this?

The second question is about Email.
Can your application send me a email ever that i recive a ticket?
I don´t have a email service, i'm using hotmail or gmail.

**Comment by tecncr** [comment]
There seems to be a bug with the timezone selector of the control panel, but you can change your timezone by editing your server's php.ini config file (e.g. /etc/php/7.4/apache2/php.ini) on the date.timezone line. Also, it's possible to set up SMTP and IMAP server config with a regular Gmail account (check Issue #982).

**Comment by alexkidrd** [comment]
Thanks for your answer!!

The first problem was sorted out!
i tried to use a diferent paramter in php. ini like this "date_default_timezone_set('America/Los_Angeles');" ​instead "date.timezone" .

I touke a look in the issue #982
it's work!

The second problem was sorted out!
Another doubt:

I noticed that I am configuring SMTP (sending), I would like to be notified and not to send emails. it is possible?
